export interface Destination {
  slug: string;
  name: string;
  region: string;
  country: string;
  lang: "fr" | "en" | "es";
  heroTitle: string;
  heroSubtitle: string;
  description: string;
  season: string;
  rateRange: string;
  rateDetail: string;
  highlights: string[];
  missionTypes: string[];
  bookingDelay: string;
  metaTitle: string;
  metaDescription: string;
  image: string;
  featured?: boolean;
  longDescription?: string;
  zones?: Array<{ name: string; description: string }>;
  faqs?: Array<{ question: string; answer: string }>;
  seoKeywords?: string[];
}

export const destinations: Destination[] = [

  // ════════════════════════════════════════════════════════════
  // CÔTE D'AZUR
  // ════════════════════════════════════════════════════════════
  {
    slug: "chef-prive-cote-azur",
    name: "Côte d'Azur", region: "Provence-Alpes-Côte d'Azur", country: "France", lang: "fr",
    heroTitle: "Chef privé Côte d'Azur",
    heroSubtitle: "Villas, yachts et résidences privées de Saint-Tropez à Monaco",
    description: "La Côte d'Azur concentre la plus forte densité de résidences privées haut de gamme d'Europe. De juin à septembre, la demande en chefs privés explose. Les meilleurs profils se réservent dès février pour la saison estivale.",
    season: "Avril — Octobre (pic juin–août)", rateRange: "3 500€ — 8 000€",
    rateDetail: "par semaine selon le nombre de convives et l'intensité du service",
    highlights: ["Chefs mobiles couvrant toute la Riviera","Profils multilingues disponibles","Expérience villas, yachts et résidences UHNW","Approvisionnement marchés locaux provençaux","Discrétion et confidentialité garanties"],
    missionTypes: ["Villa privée","Yacht","Résidence longue durée","Événement privé","Famille UHNW"],
    bookingDelay: "Réservez à l'avance pour avoir les meilleurs profils durant la haute saison",
    metaTitle: "Chef Privé Côte d'Azur | Villas & Yachts — Chefs Talents",
    metaDescription: "Trouvez un chef privé sur la Côte d'Azur pour votre villa ou yacht. Saint-Tropez, Cannes, Antibes, Monaco, Cap Ferrat. Sélection rigoureuse, discrétion totale.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=1200", featured: true,
  },
  {
    slug: "private-chef-cote-dazur",
    name: "French Riviera", region: "Provence-Alpes-Côte d'Azur", country: "France", lang: "en",
    heroTitle: "Private Chef French Riviera",
    heroSubtitle: "Villas, yachts and private residences from Saint-Tropez to Monaco",
    description: "The French Riviera has the highest concentration of high-end private residences in Europe. From June to September, demand for private chefs surges. The best profiles book out from February for the summer season.",
    season: "April — October (peak June–August)", rateRange: "€3,500 — €8,000",
    rateDetail: "per week depending on number of guests and service level",
    highlights: ["Mobile chefs covering the entire Riviera","Multilingual profiles available","Villa, yacht and UHNW residence experience","Sourcing from local Provençal markets","Absolute discretion and confidentiality"],
    missionTypes: ["Private villa","Yacht","Long-term residence","Private event","UHNW family"],
    bookingDelay: "Book early to access the best profiles during peak season",
    metaTitle: "Private Chef French Riviera | Villas & Yachts — Chefs Talents",
    metaDescription: "Find a private chef on the French Riviera for your villa or yacht. Saint-Tropez, Cannes, Antibes, Monaco, Cap Ferrat. Rigorous selection, total discretion.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=1200",
  },
  {
    slug: "chef-privado-costa-azul",
    name: "Costa Azul", region: "Provence-Alpes-Côte d'Azur", country: "Francia", lang: "es",
    heroTitle: "Chef Privado Costa Azul",
    heroSubtitle: "Villas, yates y residencias privadas de Saint-Tropez a Mónaco",
    description: "La Costa Azul concentra la mayor densidad de residencias privadas de lujo de Europa. De junio a septiembre, la demanda de chefs privados se dispara. Los mejores perfiles se reservan desde febrero para la temporada estival.",
    season: "Abril — Octubre (pico junio–agosto)", rateRange: "3.500€ — 8.000€",
    rateDetail: "por semana según el número de invitados e intensidad del servicio",
    highlights: ["Chefs móviles que cubren toda la Riviera","Perfiles multilingües disponibles","Experiencia en villas, yates y residencias UHNW","Aprovisionamiento en mercados locales provenzales","Discreción y confidencialidad absolutas"],
    missionTypes: ["Villa privada","Yate","Residencia larga duración","Evento privado","Familia UHNW"],
    bookingDelay: "Reserve con antelación para acceder a los mejores perfiles en temporada alta",
    metaTitle: "Chef Privado Costa Azul | Villas & Yates — Chefs Talents",
    metaDescription: "Encuentre un chef privado en la Costa Azul para su villa o yate. Saint-Tropez, Cannes, Antibes, Mónaco, Cap Ferrat. Selección rigurosa, discreción total.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=1200",
  },

  // ════════════════════════════════════════════════════════════
  // SAINT-TROPEZ
  // ════════════════════════════════════════════════════════════
  {
    slug: "chef-prive-saint-tropez",
    name: "Saint-Tropez", region: "Var", country: "France", lang: "fr",
    heroTitle: "Chef privé Saint-Tropez",
    heroSubtitle: "Le marché le plus exigeant de Méditerranée",
    description: "Saint-Tropez impose des standards culinaires particuliers. Les villas du golfe accueillent une clientèle habituée aux meilleures tables du monde. Le chef privé doit délivrer un niveau gastronomique constant avec une maîtrise parfaite des produits méditerranéens locaux.",
    season: "Juin — Septembre (pics juillet–août)", rateRange: "3 500€ — 8 000€",
    rateDetail: "par semaine selon le nombre de convives et l'intensité du service",
    highlights: ["Chefs formés en restaurant étoilé disponibles","Connaissance du marché de Saint-Tropez","Réseau de producteurs locaux du Var","Profils yacht pour missions mer + villa","Réservation recommandée dès mars"],
    missionTypes: ["Villa golfe de Saint-Tropez","Yacht en mouillage","Ramatuelle","Gassin","Port Grimaud"],
    bookingDelay: "Juillet–août complets dès le mois de mars pour les meilleurs profils",
    metaTitle: "Chef Privé Saint-Tropez | Villas & Yachts — Chefs Talents",
    metaDescription: "Chef privé à Saint-Tropez pour votre villa ou yacht dans le golfe. Profils gastronomiques sélectionnés, discrétion totale, coordination complète.",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=1200", featured: true,
  },
  {
    slug: "private-chef-saint-tropez",
    name: "Saint-Tropez", region: "Var", country: "France", lang: "en",
    heroTitle: "Private Chef Saint-Tropez",
    heroSubtitle: "The most demanding market in the Mediterranean",
    description: "Saint-Tropez sets particularly high culinary standards. The villas of the gulf welcome clients accustomed to the world's finest tables. The private chef must deliver consistent gastronomic quality with a perfect command of local Mediterranean produce.",
    season: "June — September (peak July–August)", rateRange: "€3,500 — €8,000",
    rateDetail: "per week depending on number of guests and service level",
    highlights: ["Michelin-trained chefs available","In-depth knowledge of Saint-Tropez market","Network of local Var producers","Yacht profiles for sea + villa missions","Book from March for peak season"],
    missionTypes: ["Saint-Tropez gulf villa","Anchored yacht","Ramatuelle","Gassin","Port Grimaud"],
    bookingDelay: "July–August fully booked from March for the best profiles",
    metaTitle: "Private Chef Saint-Tropez | Villas & Yachts — Chefs Talents",
    metaDescription: "Private chef in Saint-Tropez for your villa or yacht in the gulf. Carefully selected gastronomic profiles, total discretion, full coordination.",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=1200",
  },
  {
    slug: "chef-privado-saint-tropez",
    name: "Saint-Tropez", region: "Var", country: "Francia", lang: "es",
    heroTitle: "Chef Privado Saint-Tropez",
    heroSubtitle: "El mercado más exigente del Mediterráneo",
    description: "Saint-Tropez impone estándares culinarios particulares. Las villas del golfo acogen a una clientela acostumbrada a las mejores mesas del mundo. El chef privado debe mantener un nivel gastronómico constante con un dominio perfecto de los productos mediterráneos locales.",
    season: "Junio — Septiembre (pico julio–agosto)", rateRange: "3.500€ — 8.000€",
    rateDetail: "por semana según el número de invitados e intensidad del servicio",
    highlights: ["Chefs formados en restaurantes con estrella disponibles","Conocimiento del mercado de Saint-Tropez","Red de productores locales del Var","Perfiles yate para misiones mar + villa","Reserva recomendada desde marzo"],
    missionTypes: ["Villa golfo de Saint-Tropez","Yate en fondeadero","Ramatuelle","Gassin","Port Grimaud"],
    bookingDelay: "Julio–agosto completos desde marzo para los mejores perfiles",
    metaTitle: "Chef Privado Saint-Tropez | Villas & Yates — Chefs Talents",
    metaDescription: "Chef privado en Saint-Tropez para su villa o yate en el golfo. Perfiles gastronómicos seleccionados, discreción total, coordinación completa.",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=1200",
  },

  // ════════════════════════════════════════════════════════════
  // CANNES
  // ════════════════════════════════════════════════════════════
  {
    slug: "chef-prive-cannes",
    name: "Cannes", region: "Alpes-Maritimes", country: "France", lang: "fr",
    heroTitle: "Chef privé Cannes",
    heroSubtitle: "Villas, événements et Festival — excellence culinaire privée",
    description: "Cannes concentre une demande exceptionnelle en chefs privés, amplifiée par le Festival et les événements internationaux. Les villas des hauteurs, les yachts du Vieux-Port et les résidences du Cap d'Antibes créent un marché dense et exigeant toute l'année.",
    season: "Toute l'année (pic mai Festival + juin–août)", rateRange: "3 500€ — 8 000€",
    rateDetail: "par semaine selon le nombre de convives et l'intensité du service",
    highlights: ["Chefs privés expérimentés","Couverture Festival de Cannes en mai","Profils multilingues","Villas des hauteurs et yachts du port","Disponibilités limitées en période Festival"],
    missionTypes: ["Villa Cannes","Yacht Vieux-Port","Événement Festival","Résidence Croisette","Cap d'Antibes"],
    bookingDelay: "Festival de Cannes (mai) : réservez à l'avance",
    metaTitle: "Chef Privé Cannes | Festival & Villas — Chefs Talents",
    metaDescription: "Chef privé à Cannes pour votre villa, yacht ou événement pendant le Festival. Profils sélectionnés, disponibles toute l'année sur la Côte d'Azur.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=1200",
  },
  {
    slug: "private-chef-cannes",
    name: "Cannes", region: "Alpes-Maritimes", country: "France", lang: "en",
    heroTitle: "Private Chef Cannes",
    heroSubtitle: "Villas, events and the Film Festival — private culinary excellence",
    description: "Cannes sees exceptional demand for private chefs, amplified by the Film Festival and international events. The hilltop villas, yachts in the Old Port and Cap d'Antibes residences create a dense, year-round market.",
    season: "Year-round (peak May Festival + June–August)", rateRange: "€3,500 — €8,000",
    rateDetail: "per week depending on number of guests and service level",
    highlights: ["Experienced private chefs","Cannes Film Festival coverage in May","Multilingual profiles","Hilltop villas and port yachts","Limited availability during Festival period"],
    missionTypes: ["Cannes villa","Old Port yacht","Festival event","Croisette residence","Cap d'Antibes"],
    bookingDelay: "Cannes Film Festival (May): book well in advance",
    metaTitle: "Private Chef Cannes | Festival & Villas — Chefs Talents",
    metaDescription: "Private chef in Cannes for your villa, yacht or event during the Festival. Selected profiles, available year-round on the French Riviera.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=1200",
  },
  {
    slug: "chef-privado-cannes",
    name: "Cannes", region: "Alpes Marítimos", country: "Francia", lang: "es",
    heroTitle: "Chef Privado Cannes",
    heroSubtitle: "Villas, eventos y Festival de Cine — excelencia culinaria privada",
    description: "Cannes concentra una demanda excepcional de chefs privados, amplificada por el Festival y los eventos internacionales. Las villas en las alturas, los yates del Puerto Viejo y las residencias del Cap d'Antibes crean un mercado denso y exigente durante todo el año.",
    season: "Todo el año (pico mayo Festival + junio–agosto)", rateRange: "3.500€ — 8.000€",
    rateDetail: "por semana según el número de invitados e intensidad del servicio",
    highlights: ["Chefs privados experimentados","Cobertura Festival de Cannes en mayo","Perfiles multilingües","Villas en las alturas y yates en el puerto","Disponibilidad limitada en periodo de Festival"],
    missionTypes: ["Villa Cannes","Yate Puerto Viejo","Evento Festival","Residencia Croisette","Cap d'Antibes"],
    bookingDelay: "Festival de Cannes (mayo): reserve con mucha antelación",
    metaTitle: "Chef Privado Cannes | Festival & Villas — Chefs Talents",
    metaDescription: "Chef privado en Cannes para su villa, yate o evento durante el Festival. Perfiles seleccionados, disponibles todo el año en la Costa Azul.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=1200",
  },

  // ════════════════════════════════════════════════════════════
  // ANTIBES
  // ════════════════════════════════════════════════════════════
  {
    slug: "chef-prive-antibes",
    name: "Antibes", region: "Alpes-Maritimes", country: "France", lang: "fr",
    heroTitle: "Chef privé Antibes & Cap d'Antibes",
    heroSubtitle: "Entre pinèdes et mer — résidences discrètes et séjours longue durée",
    description: "Antibes et le Cap d'Antibes offrent un cadre plus résidentiel que Saint-Tropez. Les villas nichées dans les pinèdes accueillent des séjours souvent longs, avec une clientèle attachée à la discrétion et à la qualité du quotidien.",
    season: "Mai — Octobre", rateRange: "2 500€ — 5 000€",
    rateDetail: "par semaine selon le nombre de convives et la durée",
    highlights: ["Marché provençal d'Antibes parmi les meilleurs","Profils longue durée disponibles","Accès facile depuis Nice et Cannes","Cuisine de résidence quotidienne maîtrisée","Clientèle fidèle, chefs intégrés dans le rythme de la maison"],
    missionTypes: ["Cap d'Antibes","Juan-les-Pins","Résidence longue durée","Villa familiale","Yacht port Vauban"],
    bookingDelay: "Disponibilités plus flexibles qu'à Saint-Tropez",
    metaTitle: "Chef Privé Antibes & Cap d'Antibes — Chefs Talents",
    metaDescription: "Chef privé à Antibes et Cap d'Antibes pour villas et résidences privées. Séjours longue durée, familles UHNW, discrétion totale.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=1200",
  },
  {
    slug: "private-chef-antibes",
    name: "Antibes", region: "Alpes-Maritimes", country: "France", lang: "en",
    heroTitle: "Private Chef Antibes & Cap d'Antibes",
    heroSubtitle: "Between pine forests and the sea — discreet residences and long stays",
    description: "Antibes and Cap d'Antibes offer a more residential setting than Saint-Tropez. The villas nestled among the pine trees welcome longer stays, with clients who value discretion and consistent daily quality.",
    season: "May — October", rateRange: "€2,500 — €5,000",
    rateDetail: "per week depending on number of guests and duration",
    highlights: ["One of the best Provençal markets in the area","Long-term profiles available","Easy access from Nice and Cannes","Mastery of daily residential cuisine","Loyal clientele, chefs integrated into the household rhythm"],
    missionTypes: ["Cap d'Antibes","Juan-les-Pins","Long-term residence","Family villa","Vauban marina yacht"],
    bookingDelay: "More flexible availability than Saint-Tropez",
    metaTitle: "Private Chef Antibes & Cap d'Antibes — Chefs Talents",
    metaDescription: "Private chef in Antibes and Cap d'Antibes for villas and private residences. Long-term stays, UHNW families, total discretion.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=1200",
  },
  {
    slug: "chef-privado-antibes",
    name: "Antibes", region: "Alpes Marítimos", country: "Francia", lang: "es",
    heroTitle: "Chef Privado Antibes & Cap d'Antibes",
    heroSubtitle: "Entre pinares y el mar — residencias discretas y estancias largas",
    description: "Antibes y el Cap d'Antibes ofrecen un entorno más residencial que Saint-Tropez. Las villas entre los pinares acogen estancias frecuentemente largas, con una clientela que valora la discreción y la calidad cotidiana.",
    season: "Mayo — Octubre", rateRange: "2.500€ — 5.000€",
    rateDetail: "por semana según el número de invitados y duración",
    highlights: ["Mercado provenzal de Antibes entre los mejores","Perfiles larga duración disponibles","Fácil acceso desde Niza y Cannes","Dominio de la cocina residencial diaria","Clientela fiel, chefs integrados en el ritmo del hogar"],
    missionTypes: ["Cap d'Antibes","Juan-les-Pins","Residencia larga duración","Villa familiar","Yate puerto Vauban"],
    bookingDelay: "Disponibilidad más flexible que en Saint-Tropez",
    metaTitle: "Chef Privado Antibes & Cap d'Antibes — Chefs Talents",
    metaDescription: "Chef privado en Antibes y Cap d'Antibes para villas y residencias privadas. Estancias largas, familias UHNW, discreción total.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=1200",
  },

  // ════════════════════════════════════════════════════════════
  // MONACO
  // ════════════════════════════════════════════════════════════
  {
    slug: "chef-prive-monaco",
    name: "Monaco", region: "Principauté de Monaco", country: "Monaco", lang: "fr",
    heroTitle: "Chef privé Monaco",
    heroSubtitle: "La Principauté la plus exigeante d'Europe",
    description: "Monaco est la destination la plus exigeante d'Europe pour les chefs privés. NDA systématiques, expérience UHNW validée, présentation irréprochable. Les profils qui y opèrent ont une catégorie à part.",
    season: "Toute l'année (pic Grand Prix mai + été)", rateRange: "3 500€ — 8 000€",
    rateDetail: "par semaine, profils senior uniquement",
    highlights: ["NDA et confidentialité absolue","Références UHNW vérifiées","Expérience résidences et superyachts","Langues : FR/EN/RU selon les clients","Accès réseau Principauté maîtrisé"],
    missionTypes: ["Résidence privée","Superyacht port Hercule","Grand Prix Monaco","Penthouse","Family Office"],
    bookingDelay: "Grand Prix (mai) : réservez 6 mois à l'avance",
    metaTitle: "Chef Privé Monaco | UHNW & Superyachts — Chefs Talents",
    metaDescription: "Chef privé à Monaco pour résidences et yachts. Profils d'exception, NDA systématique, discrétion absolue. Chefs Talents — référence pour l'hospitalité privée.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1200", featured: true,
  },
  {
    slug: "private-chef-monaco",
    name: "Monaco", region: "Principality of Monaco", country: "Monaco", lang: "en",
    heroTitle: "Private Chef Monaco",
    heroSubtitle: "Europe's most demanding Principality",
    description: "Monaco is Europe's most demanding destination for private chefs. Systematic NDAs, validated UHNW experience, impeccable presentation. The profiles operating here are in a category of their own.",
    season: "Year-round (peak Grand Prix May + summer)", rateRange: "€3,500 — €8,000",
    rateDetail: "per week, senior profiles only",
    highlights: ["NDA and absolute confidentiality","Verified UHNW references","Residence and superyacht experience","Languages: FR/EN/RU depending on client","Established Principality network"],
    missionTypes: ["Private residence","Superyacht Port Hercule","Monaco Grand Prix","Penthouse","Family Office"],
    bookingDelay: "Grand Prix (May): book 6 months in advance",
    metaTitle: "Private Chef Monaco | UHNW & Superyachts — Chefs Talents",
    metaDescription: "Private chef in Monaco for residences and yachts. Exceptional profiles, systematic NDA, absolute discretion. Chefs Talents — reference for private hospitality.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1200",
  },
  {
    slug: "chef-privado-monaco",
    name: "Mónaco", region: "Principado de Mónaco", country: "Mónaco", lang: "es",
    heroTitle: "Chef Privado Mónaco",
    heroSubtitle: "El Principado más exigente de Europa",
    description: "Mónaco es el destino más exigente de Europa para los chefs privados. NDA sistemáticos, experiencia UHNW validada, presentación impecable. Los perfiles que operan aquí tienen una categoría propia.",
    season: "Todo el año (pico Gran Premio mayo + verano)", rateRange: "3.500€ — 8.000€",
    rateDetail: "por semana, solo perfiles sénior",
    highlights: ["NDA y confidencialidad absoluta","Referencias UHNW verificadas","Experiencia en residencias y superyates","Idiomas: FR/EN/RU según el cliente","Red establecida en el Principado"],
    missionTypes: ["Residencia privada","Superyate Puerto Hércules","Gran Premio de Mónaco","Ático","Family Office"],
    bookingDelay: "Gran Premio (mayo): reserve con 6 meses de antelación",
    metaTitle: "Chef Privado Mónaco | UHNW & Superyates — Chefs Talents",
    metaDescription: "Chef privado en Mónaco para residencias y yates. Perfiles de excepción, NDA sistemático, discreción absoluta.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1200",
  },

  // ════════════════════════════════════════════════════════════
  // NICE
  // ════════════════════════════════════════════════════════════
  {
    slug: "chef-prive-nice",
    name: "Nice", region: "Alpes-Maritimes", country: "France", lang: "fr",
    heroTitle: "Chef privé Nice",
    heroSubtitle: "Entre mer et collines — résidences et villas niçoises",
    description: "Nice est la capitale de la Côte d'Azur et un hub logistique pour les missions de toute la Riviera. Les chefs basés à Nice interviennent sur l'ensemble du territoire — Antibes, Cannes, Monaco, Cap Ferrat.",
    season: "Toute l'année", rateRange: "2 500€ — 5 000€",
    rateDetail: "par semaine selon le nombre de convives et la durée",
    highlights: ["Hub logistique pour toute la Côte d'Azur","Marché du Cours Saleya produits exceptionnels","Profils disponibles toute l'année","Mont Boron, Cimiez, arrière-pays niçois"],
    missionTypes: ["Villa Nice","Résidence Cimiez","Mont Boron","Arrière-pays niçois","Mission courte"],
    bookingDelay: "Disponibilités flexibles hors saison",
    metaTitle: "Chef Privé Nice | Villas & Résidences | Chefs Talents",
    metaDescription: "Chef privé à Nice pour villas et résidences privées. Cuisine niçoise et gastronomique.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=1200",
  },
  {
    slug: "private-chef-nice",
    name: "Nice", region: "Alpes-Maritimes", country: "France", lang: "en",
    heroTitle: "Private Chef Nice",
    heroSubtitle: "Between sea and hills — villas and residences in Nice",
    description: "Nice is the capital of the French Riviera and a logistical hub for missions across the region. Chefs based in Nice cover the entire territory — Antibes, Cannes, Monaco, Cap Ferrat.",
    season: "Year-round", rateRange: "€2,500 — €5,000",
    rateDetail: "per week depending on number of guests and duration",
    highlights: ["Logistical hub for the entire French Riviera","Exceptional Cours Saleya market produce","Year-round available profiles","Mont Boron, Cimiez, Nice hinterland"],
    missionTypes: ["Nice villa","Cimiez residence","Mont Boron","Nice hinterland","Short mission"],
    bookingDelay: "Flexible availability outside peak season",
    metaTitle: "Private Chef Nice | Villas & Residences | Chefs Talents",
    metaDescription: "Private chef in Nice for villas and private residences. Niçoise and gastronomic cuisine.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=1200",
  },
  {
    slug: "chef-privado-niza",
    name: "Niza", region: "Alpes Marítimos", country: "Francia", lang: "es",
    heroTitle: "Chef Privado Niza",
    heroSubtitle: "Entre el mar y las colinas — villas y residencias en Niza",
    description: "Niza es la capital de la Costa Azul y un hub logístico para las misiones de toda la región. Los chefs con base en Niza cubren todo el territorio — Antibes, Cannes, Mónaco, Cap Ferrat.",
    season: "Todo el año", rateRange: "2.500€ — 5.000€",
    rateDetail: "por semana según el número de invitados y duración",
    highlights: ["Hub logístico para toda la Costa Azul","Mercado del Cours Saleya con productos excepcionales","Perfiles disponibles todo el año","Mont Boron, Cimiez, interior de Niza"],
    missionTypes: ["Villa Niza","Residencia Cimiez","Mont Boron","Interior de Niza","Misión corta"],
    bookingDelay: "Disponibilidad flexible fuera de temporada",
    metaTitle: "Chef Privado Niza | Villas & Residencias | Chefs Talents",
    metaDescription: "Chef privado en Niza para villas y residencias privadas. Cocina nizarda y gastronómica.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=1200",
  },

  // ════════════════════════════════════════════════════════════
  // CAP FERRAT
  // ════════════════════════════════════════════════════════════
  {
    slug: "chef-prive-cap-ferrat",
    name: "Cap Ferrat", region: "Alpes-Maritimes", country: "France", lang: "fr",
    heroTitle: "Chef privé Cap Ferrat",
    heroSubtitle: "La presqu'île la plus exclusive de France",
    description: "Le Cap Ferrat est la presqu'île la plus exclusive de France. Entre Nice et Monaco, ses villas centenaires accueillent une clientèle parmi les plus discrètes et les plus exigeantes de la Côte d'Azur.",
    season: "Mai — Octobre (résidences toute l'année)", rateRange: "3 500€ — 8 000€",
    rateDetail: "par semaine, missions souvent longue durée",
    highlights: ["Résidences longue durée fréquentes","Clientèle ultra-discrète et fidèle","Intégration dans le rythme de la maison","Profils habitués aux environnements UHNW"],
    missionTypes: ["Villa Cap Ferrat","Résidence longue durée","Famille UHNW","Mission saisonnière","Villefranche-sur-Mer"],
    bookingDelay: "Missions souvent réservées plusieurs mois à l'avance",
    metaTitle: "Chef Privé Cap Ferrat | Villas d'Exception — Chefs Talents",
    metaDescription: "Chef privé au Cap Ferrat pour villas et résidences privées. La presqu'île la plus exclusive de France. Discrétion absolue, intégration longue durée.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=1200",
  },
  {
    slug: "private-chef-cap-ferrat",
    name: "Cap Ferrat", region: "Alpes-Maritimes", country: "France", lang: "en",
    heroTitle: "Private Chef Cap Ferrat",
    heroSubtitle: "France's most exclusive peninsula",
    description: "Cap Ferrat is France's most exclusive peninsula. Between Nice and Monaco, its century-old villas welcome some of the most discreet and demanding clients on the French Riviera.",
    season: "May — October (year-round residences)", rateRange: "€3,500 — €8,000",
    rateDetail: "per week, often long-term missions",
    highlights: ["Frequent long-term residence missions","Ultra-discreet and loyal clientele","Integration into the household rhythm","Profiles accustomed to UHNW environments"],
    missionTypes: ["Cap Ferrat villa","Long-term residence","UHNW family","Seasonal mission","Villefranche-sur-Mer"],
    bookingDelay: "Missions often booked several months in advance",
    metaTitle: "Private Chef Cap Ferrat | Exceptional Villas — Chefs Talents",
    metaDescription: "Private chef at Cap Ferrat for villas and private residences. France's most exclusive peninsula. Absolute discretion, long-term integration.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=1200",
  },
  {
    slug: "chef-privado-cap-ferrat",
    name: "Cap Ferrat", region: "Alpes Marítimos", country: "Francia", lang: "es",
    heroTitle: "Chef Privado Cap Ferrat",
    heroSubtitle: "La península más exclusiva de Francia",
    description: "Cap Ferrat es la península más exclusiva de Francia. Entre Niza y Mónaco, sus villas centenarias acogen a algunos de los clientes más discretos y exigentes de la Costa Azul.",
    season: "Mayo — Octubre (residencias todo el año)", rateRange: "3.500€ — 8.000€",
    rateDetail: "por semana, misiones frecuentemente de larga duración",
    highlights: ["Misiones en residencia larga duración frecuentes","Clientela ultra-discreta y fiel","Integración en el ritmo del hogar","Perfiles habituados a entornos UHNW"],
    missionTypes: ["Villa Cap Ferrat","Residencia larga duración","Familia UHNW","Misión de temporada","Villefranche-sur-Mer"],
    bookingDelay: "Misiones frecuentemente reservadas con varios meses de antelación",
    metaTitle: "Chef Privado Cap Ferrat | Villas de Excepción — Chefs Talents",
    metaDescription: "Chef privado en Cap Ferrat para villas y residencias privadas. La península más exclusiva de Francia. Discreción absoluta, integración a largo plazo.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=1200",
  },

  // ════════════════════════════════════════════════════════════
  // COURCHEVEL
  // ════════════════════════════════════════════════════════════
  {
    slug: "chef-prive-courchevel",
    name: "Courchevel", region: "Savoie", country: "France", lang: "fr",
    heroTitle: "Chef privé Courchevel",
    heroSubtitle: "Chalets de luxe et gastronomie alpine — saison ski",
    description: "Courchevel 1850 est la station la plus prestigieuse des Alpes françaises. Les chalets du Jardin Alpin accueillent une clientèle internationale dont les attentes culinaires rivalisent avec les meilleures tables parisiennes. Les meilleurs chefs sont réservés 6 à 12 mois à l'avance.",
    season: "Décembre — Avril (Noël/Nouvel An + février)", rateRange: "3 500€ — 8 000€",
    rateDetail: "par semaine, tarif maximum période Noël",
    highlights: ["Chefs formés haute cuisine disponibles","Maîtrise pâtisserie fine pour tea-times","Expérience cuisine d'altitude validée","Langues : FR/EN/RU selon les chalets"],
    missionTypes: ["Chalet Courchevel 1850","Jardin Alpin","Bellecôte","Famille ski","Nouvel An"],
    bookingDelay: "Noël/Nouvel An : réservez à l'avance",
    metaTitle: "Chef Privé Courchevel | Chalets de Luxe | Chefs Talents",
    metaDescription: "Chef privé à Courchevel 1850 pour votre chalet de luxe. Gastronomie alpine, tea-times, dîners d'exception après le ski. Sélection rigoureuse.",
    image: "https://images.unsplash.com/photo-1516571589254-46487e38c92a?q=80&w=1200", featured: true,
  },
  {
    slug: "private-chef-courchevel",
    name: "Courchevel", region: "Savoie", country: "France", lang: "en",
    heroTitle: "Private Chef Courchevel",
    heroSubtitle: "Luxury chalets and alpine gastronomy — ski season",
    description: "Courchevel 1850 is the most prestigious resort in the French Alps. The Jardin Alpin chalets welcome an international clientele whose culinary expectations rival the finest Parisian restaurants. The best chefs book out 6 to 12 months in advance.",
    season: "December — April (Christmas/New Year + February)", rateRange: "€3,500 — €8,000",
    rateDetail: "per week, maximum rate over Christmas period",
    highlights: ["Haute cuisine trained chefs available","Fine patisserie for tea-times","Validated high-altitude cooking experience","Languages: FR/EN/RU depending on chalet"],
    missionTypes: ["Courchevel 1850 chalet","Jardin Alpin","Bellecôte","Ski family","New Year's Eve"],
    bookingDelay: "Christmas/New Year: book well in advance",
    metaTitle: "Private Chef Courchevel | Luxury Chalets | Chefs Talents",
    metaDescription: "Private chef in Courchevel 1850 for your luxury chalet. Alpine gastronomy, tea-times, exceptional après-ski dinners. Rigorous selection.",
    image: "https://images.unsplash.com/photo-1516571589254-46487e38c92a?q=80&w=1200",
  },
  {
    slug: "chef-privado-courchevel",
    name: "Courchevel", region: "Saboya", country: "Francia", lang: "es",
    heroTitle: "Chef Privado Courchevel",
    heroSubtitle: "Chalets de lujo y gastronomía alpina — temporada de esquí",
    description: "Courchevel 1850 es la estación más prestigiosa de los Alpes franceses. Los chalets del Jardin Alpin acogen a una clientela internacional cuyas expectativas culinarias rivalizan con los mejores restaurantes parisinos. Los mejores chefs se reservan de 6 a 12 meses de antelación.",
    season: "Diciembre — Abril (Navidad/Año Nuevo + febrero)", rateRange: "3.500€ — 8.000€",
    rateDetail: "por semana, tarifa máxima en periodo navideño",
    highlights: ["Chefs formados en alta cocina disponibles","Dominio de la repostería fina para tea-times","Experiencia en cocina de altitud validada","Idiomas: FR/EN/RU según el chalet"],
    missionTypes: ["Chalet Courchevel 1850","Jardin Alpin","Bellecôte","Familia esquí","Nochevieja"],
    bookingDelay: "Navidad/Año Nuevo: reserve con mucha antelación",
    metaTitle: "Chef Privado Courchevel | Chalets de Lujo | Chefs Talents",
    metaDescription: "Chef privado en Courchevel 1850 para su chalet de lujo. Gastronomía alpina, tea-times, cenas excepcionales après-ski. Selección rigurosa.",
    image: "https://images.unsplash.com/photo-1516571589254-46487e38c92a?q=80&w=1200",
  },

  // ════════════════════════════════════════════════════════════
  // MEGÈVE
  // ════════════════════════════════════════════════════════════
  {
    slug: "chef-prive-megeve",
    name: "Megève", region: "Haute-Savoie", country: "France", lang: "fr",
    heroTitle: "Chef privé Megève",
    heroSubtitle: "La station la plus élégante des Alpes françaises",
    description: "Megève cultive un art de vivre discret et raffiné où la gastronomie occupe une place centrale. Entourée de producteurs d'exception — fromagers de Haute-Savoie, charcutiers savoyards — la destination impose un chef qui sait travailler le terroir.",
    season: "Décembre — Mars + Juillet — Août", rateRange: "2 500€ — 5 000€",
    rateDetail: "par semaine selon la saison et le nombre de convives",
    highlights: ["Cuisine terroir savoyard et gastronomique","Profils avec sensibilité cuisine de saison","Ambiance chalet intime et raffinée","Double saison ski + été disponible"],
    missionTypes: ["Chalet Megève","Résidence ski","Mission été","Famille longue durée","Événement privé"],
    bookingDelay: "Saison ski : réservez plusieurs mois à l'avance pour avoir accès aux meilleurs profils",
    metaTitle: "Chef Privé Megève | Chalets & Art de Vivre Alpin | Chefs Talents",
    metaDescription: "Chef privé à Megève pour votre chalet. Cuisine savoyarde et gastronomique, tea-times, dîners après le ski. La station la plus élégante des Alpes.",
    image: "https://images.unsplash.com/photo-1516571589254-46487e38c92a?q=80&w=1200",
  },
  {
    slug: "private-chef-megeve",
    name: "Megève", region: "Haute-Savoie", country: "France", lang: "en",
    heroTitle: "Private Chef Megève",
    heroSubtitle: "The most elegant resort in the French Alps",
    description: "Megève cultivates a discreet and refined art de vivre where gastronomy takes centre stage. Surrounded by exceptional producers — Haute-Savoie cheesemakers, Savoyard charcutiers — the destination calls for a chef who knows how to work with local terroir.",
    season: "December — March + July — August", rateRange: "€2,500 — €5,000",
    rateDetail: "per week depending on season and number of guests",
    highlights: ["Savoyard terroir and gastronomic cuisine","Profiles with seasonal cooking sensibility","Intimate and refined chalet atmosphere","Double ski + summer season available"],
    missionTypes: ["Megève chalet","Ski residence","Summer mission","Long-term family","Private event"],
    bookingDelay: "Ski season: book several months in advance for the best profiles",
    metaTitle: "Private Chef Megève | Chalets & Alpine Living | Chefs Talents",
    metaDescription: "Private chef in Megève for your chalet. Savoyard and gastronomic cuisine, tea-times, après-ski dinners. The most elegant resort in the Alps.",
    image: "https://images.unsplash.com/photo-1516571589254-46487e38c92a?q=80&w=1200",
  },
  {
    slug: "chef-privado-megeve",
    name: "Megève", region: "Alta Saboya", country: "Francia", lang: "es",
    heroTitle: "Chef Privado Megève",
    heroSubtitle: "La estación más elegante de los Alpes franceses",
    description: "Megève cultiva un arte de vivir discreto y refinado donde la gastronomía ocupa un lugar central. Rodeada de productores excepcionales — queseros de Alta Saboya, charcuteros savoyardos — el destino requiere un chef que sepa trabajar el terroir local.",
    season: "Diciembre — Marzo + Julio — Agosto", rateRange: "2.500€ — 5.000€",
    rateDetail: "por semana según la temporada y el número de invitados",
    highlights: ["Cocina de terroir saboyardo y gastronómica","Perfiles con sensibilidad de cocina de temporada","Ambiente de chalet íntimo y refinado","Doble temporada esquí + verano disponible"],
    missionTypes: ["Chalet Megève","Residencia esquí","Misión verano","Familia larga duración","Evento privado"],
    bookingDelay: "Temporada esquí: reserve con varios meses de antelación para los mejores perfiles",
    metaTitle: "Chef Privado Megève | Chalets & Arte de Vivir Alpino | Chefs Talents",
    metaDescription: "Chef privado en Megève para su chalet. Cocina saboyarda y gastronómica, tea-times, cenas après-ski. La estación más elegante de los Alpes.",
    image: "https://images.unsplash.com/photo-1516571589254-46487e38c92a?q=80&w=1200",
  },

  // ════════════════════════════════════════════════════════════
  // VAL D'ISÈRE
  // ════════════════════════════════════════════════════════════
  {
    slug: "chef-prive-val-disere",
    name: "Val d'Isère", region: "Savoie", country: "France", lang: "fr",
    heroTitle: "Chef privé Val d'Isère",
    heroSubtitle: "Chalets d'exception en Tarentaise — saison ski",
    description: "Val d'Isère attire une clientèle sportive et internationale dans des chalets parmi les plus luxueux des Alpes. L'altitude (1 850m) et l'enclavement imposent une logistique rigoureuse que seuls les chefs expérimentés maîtrisent.",
    season: "Décembre — Avril", rateRange: "2 500€ — 5 000€",
    rateDetail: "par semaine selon la période et le nombre de convives",
    highlights: ["Logistique altitude maîtrisée","Petits-déjeuners denses avant les pistes","Tea-times et dîners gastronomiques"],
    missionTypes: ["Chalet Val d'Isère","Famille ski","Nouvel An","Séjour sportif","Mission semaine"],
    bookingDelay: "Noël/Nouvel An : réservez 6 mois à l'avance",
    metaTitle: "Chef Privé Val d'Isère | Chalets de Luxe | Chefs Talents",
    metaDescription: "Chef privé à Val d'Isère pour votre chalet de luxe. Logistique altitude maîtrisée, gastronomie alpine, disponible toute la saison ski.",
    image: "https://images.unsplash.com/photo-1516571589254-46487e38c92a?q=80&w=1200",
  },
  {
    slug: "private-chef-val-disere",
    name: "Val d'Isère", region: "Savoie", country: "France", lang: "en",
    heroTitle: "Private Chef Val d'Isère",
    heroSubtitle: "Exceptional chalets in the Tarentaise — ski season",
    description: "Val d'Isère attracts a sporty, international clientele to some of the Alps' most luxurious chalets. The altitude (1,850m) and remoteness demand rigorous logistics that only experienced chefs can handle.",
    season: "December — April", rateRange: "€2,500 — €5,000",
    rateDetail: "per week depending on period and number of guests",
    highlights: ["Mastered high-altitude logistics","Hearty pre-ski breakfasts","Tea-times and gastronomic dinners"],
    missionTypes: ["Val d'Isère chalet","Ski family","New Year's Eve","Sports stay","Weekly mission"],
    bookingDelay: "Christmas/New Year: book 6 months in advance",
    metaTitle: "Private Chef Val d'Isère | Luxury Chalets | Chefs Talents",
    metaDescription: "Private chef in Val d'Isère for your luxury chalet. Mastered high-altitude logistics, alpine gastronomy, available throughout the ski season.",
    image: "https://images.unsplash.com/photo-1516571589254-46487e38c92a?q=80&w=1200",
  },
  {
    slug: "chef-privado-val-disere",
    name: "Val d'Isère", region: "Saboya", country: "Francia", lang: "es",
    heroTitle: "Chef Privado Val d'Isère",
    heroSubtitle: "Chalets de excepción en Tarentaise — temporada esquí",
    description: "Val d'Isère atrae a una clientela deportiva e internacional a algunos de los chalets más lujosos de los Alpes. La altitud (1.850m) y el aislamiento imponen una logística rigurosa que solo los chefs experimentados dominan.",
    season: "Diciembre — Abril", rateRange: "2.500€ — 5.000€",
    rateDetail: "por semana según el periodo y número de invitados",
    highlights: ["Logística de altitud dominada","Desayunos abundantes antes de las pistas","Tea-times y cenas gastronómicas"],
    missionTypes: ["Chalet Val d'Isère","Familia esquí","Nochevieja","Estancia deportiva","Misión semanal"],
    bookingDelay: "Navidad/Año Nuevo: reserve con 6 meses de antelación",
    metaTitle: "Chef Privado Val d'Isère | Chalets de Lujo | Chefs Talents",
    metaDescription: "Chef privado en Val d'Isère para su chalet de lujo. Logística de altitud dominada, gastronomía alpina, disponible toda la temporada de esquí.",
    image: "https://images.unsplash.com/photo-1516571589254-46487e38c92a?q=80&w=1200",
  },

  // ════════════════════════════════════════════════════════════
  // BIARRITZ
  // ════════════════════════════════════════════════════════════
  {
    slug: "chef-prive-biarritz",
    name: "Biarritz", region: "Pays Basque", country: "France", lang: "fr",
    heroTitle: "Chef privé Biarritz",
    heroSubtitle: "Villas basques et Côte d'Argent — gastronomie du Pays Basque",
    description: "Biarritz et la Côte basque constituent un marché en forte croissance. Les villas des hauteurs accueillent une clientèle parisienne et internationale attirée par le terroir gastronomique exceptionnel du Pays Basque.",
    season: "Juin — Septembre + week-ends toute l'année", rateRange: "2 500€ — 5 000€",
    rateDetail: "par semaine selon le nombre de convives et le profil",
    highlights: ["Thon rouge de Saint-Jean-de-Luz en saison","Cuisine basque contemporaine maîtrisée","Palombe et produits de saison","Marché des Halles de Biarritz"],
    missionTypes: ["Villa Biarritz","Saint-Jean-de-Luz","Anglet","Résidence côtière","Événement basque"],
    bookingDelay: "Juillet–août : réservez 2 mois à l'avance",
    metaTitle: "Chef Privé Biarritz & Pays Basque — Chefs Talents",
    metaDescription: "Chef privé à Biarritz pour votre villa sur la Côte basque. Gastronomie basque, produits locaux d'exception, discrétion totale.",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=1200",
  },
  {
    slug: "private-chef-biarritz",
    name: "Biarritz", region: "Basque Country", country: "France", lang: "en",
    heroTitle: "Private Chef Biarritz",
    heroSubtitle: "Basque villas and the Silver Coast — Basque Country gastronomy",
    description: "Biarritz and the Basque Coast represent a fast-growing market. The hilltop villas welcome Parisian and international clients drawn by the exceptional gastronomic terroir of the Basque Country.",
    season: "June — September + weekends year-round", rateRange: "€2,500 — €5,000",
    rateDetail: "per week depending on number of guests and profile",
    highlights: ["Red tuna from Saint-Jean-de-Luz in season","Contemporary Basque cuisine mastered","Wood pigeon and seasonal produce","Biarritz Halles market"],
    missionTypes: ["Biarritz villa","Saint-Jean-de-Luz","Anglet","Coastal residence","Basque event"],
    bookingDelay: "July–August: book 2 months in advance",
    metaTitle: "Private Chef Biarritz & Basque Country — Chefs Talents",
    metaDescription: "Private chef in Biarritz for your villa on the Basque Coast. Basque gastronomy, exceptional local produce, total discretion.",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=1200",
  },
  {
    slug: "chef-privado-biarritz",
    name: "Biarritz", region: "País Vasco", country: "Francia", lang: "es",
    heroTitle: "Chef Privado Biarritz",
    heroSubtitle: "Villas vascas y la Costa de Plata — gastronomía del País Vasco",
    description: "Biarritz y la Costa Vasca constituyen un mercado en fuerte crecimiento. Las villas en las alturas acogen a una clientela parisina e internacional atraída por el excepcional terroir gastronómico del País Vasco.",
    season: "Junio — Septiembre + fines de semana todo el año", rateRange: "2.500€ — 5.000€",
    rateDetail: "por semana según el número de invitados y el perfil",
    highlights: ["Atún rojo de Saint-Jean-de-Luz en temporada","Cocina vasca contemporánea dominada","Paloma y productos de temporada","Mercado de los Halles de Biarritz"],
    missionTypes: ["Villa Biarritz","Saint-Jean-de-Luz","Anglet","Residencia costera","Evento vasco"],
    bookingDelay: "Julio–agosto: reserve con 2 meses de antelación",
    metaTitle: "Chef Privado Biarritz & País Vasco — Chefs Talents",
    metaDescription: "Chef privado en Biarritz para su villa en la Costa Vasca. Gastronomía vasca, productos locales excepcionales, discreción total.",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=1200",
  },

  // ════════════════════════════════════════════════════════════
  // IBIZA — FR / EN / ES (données enrichies existantes)
  // ════════════════════════════════════════════════════════════
  {
    slug: "private-chef-ibiza",
    name: "Ibiza", region: "Balearic Islands", country: "Spain", lang: "en",
    heroTitle: "Private Chef Ibiza",
    heroSubtitle: "50+ vetted chefs for villas, yachts and private residences in Ibiza",
    description: "Ibiza has become one of the most in-demand destinations in the Mediterranean for private chef hire. With 50+ active chefs in our network across the island, Chefs Talents is the premium French-curated service for luxury villas, yachts and private residences in Ibiza. Season runs May to September — the best profiles book out from January.",
    season: "May — September (peak June–August)", rateRange: "€3,500 — €7,000",
    rateDetail: "per week depending on profile, number of guests, duration and service level",
    highlights: ["50+ active chefs in our vetted network on the island","Mediterranean, plant-based, Japanese and international cuisine","Multilingual chefs: EN/ES/FR/IT available","Villa, yacht and superyacht experience","Coverage across Ibiza Town, Sant Antoni, Santa Gertrudis, Es Cubells, Formentera","Fresh sourcing from Ibiza Vila market and local producers","Chefs experienced with UHNW standards"],
    missionTypes: ["Ibiza villa","Yacht & superyacht","Full season","Weekly stay","Formentera","Private event","Long-term residence"],
    bookingDelay: "Book by January for July–August. June and September: available until April–May. Last-minute possible but limited.",
    metaTitle: "Private Chef Ibiza | 50+ Vetted Chefs | Villas & Yachts — Chefs Talents",
    metaDescription: "Hire a private chef in Ibiza for your luxury villa or yacht. 50+ vetted chefs in our network. Tailored menus, multilingual profiles, available May to September. Response within 6 hours.",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?q=80&w=1200", featured: true,
    longDescription: `Ibiza is no longer just a party island. Over the past few years, it has established itself as one of the most demanding private destinations in the Mediterranean. The luxury villas of Es Cubells, the fincas of Santa Gertrudis, the hilltop properties of Sant Josep — environments where the culinary experience has become just as important as the setting itself.

Chefs Talents has 50+ active chefs in its network across the island. Profiles who know Ibiza — its markets, its producers, its rhythms — and who know how to meet the expectations of an international clientele accustomed to the world's finest tables.

The active season runs from May to September, peaking in July and August. Demand is extremely concentrated during this window. The best profiles are booked from January by returning clients. If you're planning a villa or yacht this summer, reach out now.`,
    zones: [{ name: "Es Cubells & Sant Josep", description: "Sea-view villas, ultra-discreet clientele" },{ name: "Santa Gertrudis", description: "Interior fincas and residences, long-stay missions" },{ name: "Ibiza Town & Talamanca", description: "Villas near the port, cosmopolitan clientele" },{ name: "Sant Antoni", description: "Coastal villas, Café del Mar sunset dinners" },{ name: "Formentera", description: "Villa service and inter-island transfers from Ibiza" },{ name: "Yachts & marinas", description: "Marina Botafoch, Puerto Deportivo, private anchorages" }],
    faqs: [{ question: "How much does a private chef cost in Ibiza?", answer: "A private chef in Ibiza typically costs between €3,500 and €7,000 per week depending on the profile, number of guests, service level and duration. For a one-off dinner, prices start from €600 for 6 guests. For full daily service (breakfast, lunch, dinner), senior profiles range from €800 to €1,500 per day all-inclusive — groceries, preparation, service and clean-up included." },{ question: "What's the difference between Chefs Talents and Take a Chef in Ibiza?", answer: "Take a Chef is an open marketplace with 467 profiles starting from €60 per person. Chefs Talents is a curated selection of 50+ personally vetted chefs, with human coordination and a response guarantee within 6 hours. We work with clients where quality, continuity and discretion come first — high-end villas, yachts, long-term missions." },{ question: "Can I hire a private chef on a yacht in Ibiza?", answer: "Yes. Several profiles in our Ibiza network have validated yachting experience — marina provisioning, cooking in confined spaces, service at sea. We cover yachts berthed at Marina Botafoch, Puerto Deportivo, and anchorages in Ibiza Bay or around Formentera." },{ question: "How far in advance do I need to book a private chef for summer in Ibiza?", answer: "The best profiles book out from January for peak season (July–August). For June or September, availability remains accessible until April–May. Last-minute requests are possible but availability is severely limited in high summer. We always do our best to find a solution." },{ question: "Do your chefs in Ibiza speak English?", answer: "Yes. The majority of profiles in our Ibiza network are multilingual. Depending on the mission, we match chefs who communicate in English, Spanish, French and sometimes Italian. The client's language is always factored into our matching process." },{ question: "Does Chefs Talents cover Formentera?", answer: "Yes. Several chefs in our network work regularly in Formentera. The transfer from Ibiza is factored into the coordination. Contact us with your specific request." }],
    seoKeywords: ["private chef Ibiza","hire private chef Ibiza","private chef ibiza villa","private chef ibiza yacht","personal chef ibiza","chef hire ibiza","private chef formentera","luxury chef ibiza","ibiza villa chef","private chef balearic islands"],
  },
  {
    slug: "chef-prive-ibiza",
    name: "Ibiza", region: "Îles Baléares", country: "Espagne", lang: "fr",
    heroTitle: "Chef privé Ibiza",
    heroSubtitle: "Plus de 50 chefs sélectionnés pour villas, yachts et résidences aux Baléares",
    description: "Ibiza s'est imposée comme l'une des destinations les plus demandées de Méditerranée pour les chefs privés. Avec plus de 50 chefs actifs dans notre réseau sur l'île, Chefs Talents est la référence française pour les villas de luxe, yachts et résidences privées à Ibiza. Saison concentrée de mai à septembre : les meilleurs profils se réservent dès janvier.",
    season: "Mai — Septembre (pic juin–août)", rateRange: "3 500€ — 7 000€",
    rateDetail: "par semaine selon le profil, le nombre de personnes, la durée et l'intensité du service",
    highlights: ["50+ chefs actifs dans notre réseau sur l'île","Cuisine méditerranéenne, végane, internationale, japonaise","Profils multilingues ES/EN/FR/IT disponibles","Expérience villas, yachts et superyachts","Couverture Ibiza Town, Sant Antoni, Santa Gertrudis, Es Cubells, Formentera","Approvisionnement marché d'Ibiza Vila et producteurs locaux","Chefs habitués aux standards UHNW"],
    missionTypes: ["Villa Ibiza","Yacht et superyacht","Saison complète","Séjour semaine","Formentera","Événement privé","Résidence longue durée"],
    bookingDelay: "Réservez avant janvier pour juillet–août. Juin et septembre : disponible jusqu'en avril–mai. Dernière minute possible mais limitée.",
    metaTitle: "Chef Privé Ibiza | 50+ Chefs Sélectionnés | Villas & Yachts — Chefs Talents",
    metaDescription: "Chef privé à Ibiza pour votre villa ou yacht de luxe. Plus de 50 chefs sélectionnés dans notre réseau. Cuisine sur-mesure, profils multilingues, disponibles de mai à septembre. Réponse en 6h.",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?q=80&w=1200", featured: true,
    longDescription: `Ibiza n'est plus seulement une île de fête. Depuis plusieurs années, elle s'est imposée comme l'une des destinations privées les plus exigeantes de Méditerranée. Les villas de luxe d'Es Cubells, les fincas de Santa Gertrudis, les propriétés avec vue de Sant Josep — autant d'environnements où l'expérience culinaire est devenue aussi importante que le cadre.

Chefs Talents dispose de plus de 50 chefs actifs dans son réseau sur l'île. Des profils qui connaissent Ibiza — ses marchés, ses producteurs, ses rythmes — et qui savent s'adapter aux exigences d'une clientèle internationale habituée aux meilleures tables du monde.

La saison active dure de mai à septembre, avec un pic en juillet et août. La demande est extrêmement concentrée sur cette période. Les meilleurs profils sont réservés dès janvier par des clients réguliers. Si vous prévoyez une villa ou un yacht cet été, contactez-nous maintenant.`,
    zones: [{ name: "Es Cubells & Sant Josep", description: "Villas avec vue mer, clientèle ultra-discrète" },{ name: "Santa Gertrudis", description: "Fincas et résidences intérieures, séjours longue durée" },{ name: "Ibiza Town & Talamanca", description: "Villas proches du port, clientèle cosmopolite" },{ name: "Sant Antoni", description: "Villas côtières, couchers de soleil Café del Mar" },{ name: "Formentera", description: "Villas et transferts inter-îles, accessible depuis Ibiza" },{ name: "Yachts & ports", description: "Marina Botafoch, Puerto Deportivo, mouillages privés" }],
    faqs: [{ question: "Combien coûte un chef privé à Ibiza ?", answer: "Le tarif d'un chef privé à Ibiza varie entre 3 500€ et 7 000€ par semaine selon le profil, le nombre de convives, le niveau de service et la durée de la mission. Pour un dîner ponctuel, comptez à partir de 600€ pour 6 personnes. Pour une présence quotidienne (petit-déjeuner, déjeuner, dîner), les profils seniors se situent entre 700€ et 1 500€ par jour tout compris. Ces tarifs incluent les courses, la préparation, le service et le nettoyage." },{ question: "Quelle est la différence entre Chefs Talents et Take a Chef à Ibiza ?", answer: "Take a Chef est une marketplace ouverte à tous les profils à partir de 60€ par personne. Chefs Talents est une sélection de 50+ chefs vérifiés, avec une coordination humaine et une réponse garantie en moins de 6 heures. Nous intervenons pour des missions où la qualité, la continuité et la discrétion priment — villas haut de gamme, yachts, missions longue durée." },{ question: "Peut-on avoir un chef privé sur un yacht à Ibiza ?", answer: "Oui. Plusieurs profils de notre réseau ibicenco ont une expérience yachting validée — approvisionnement en port, cuisine en espace contraint, service à la mer. Nous couvrons les yachts à quai à Marina Botafoch, Puerto Deportivo, et les mouillages dans la baie d'Ibiza ou autour de Formentera." },{ question: "Jusqu'à quand peut-on réserver un chef privé pour l'été à Ibiza ?", answer: "Les meilleurs profils sont réservés dès janvier pour la haute saison (juillet–août). Si vous cherchez pour juin ou septembre, des disponibilités restent accessibles jusqu'en avril–mai. En cas de besoin de dernière minute, nous faisons notre possible pour trouver une solution, mais les disponibilités sont fortement réduites en plein été." },{ question: "Les chefs de Chefs Talents à Ibiza parlent-ils anglais ?", answer: "La majorité des profils de notre réseau ibicenco sont multilingues. Selon les missions, nous sélectionnons des chefs capables de communiquer en espagnol, anglais, français et parfois italien. La langue du client est toujours prise en compte lors du matching." },{ question: "Est-ce que Chefs Talents couvre Formentera ?", answer: "Oui. Plusieurs chefs de notre réseau interviennent régulièrement à Formentera. Le déplacement depuis Ibiza est intégré dans la coordination. Contactez-nous pour votre demande spécifique." }],
    seoKeywords: ["chef privé Ibiza","private chef Ibiza","chef cuisiner villa Ibiza","chef yacht Ibiza","cuisinier privé Ibiza","chef à domicile Ibiza","hire private chef Ibiza","chef Formentera","chef privé Baléares"],
  },
  {
    slug: "chef-privado-ibiza",
    name: "Ibiza", region: "Islas Baleares", country: "España", lang: "es",
    heroTitle: "Chef Privado Ibiza",
    heroSubtitle: "Más de 50 chefs seleccionados para villas, yates y residencias privadas en Ibiza",
    description: "Ibiza se ha convertido en uno de los destinos más solicitados del Mediterráneo para la contratación de chefs privados. Con más de 50 chefs activos en nuestra red en la isla, Chefs Talents es el servicio de referencia para villas de lujo, yates y residencias privadas en Ibiza. La temporada activa va de mayo a septiembre — los mejores perfiles se reservan desde enero.",
    season: "Mayo — Septiembre (pico junio–agosto)", rateRange: "3.500€ — 7.000€",
    rateDetail: "por semana según el perfil, número de invitados, duración e intensidad del servicio",
    highlights: ["Más de 50 chefs activos en nuestra red en la isla","Cocina mediterránea, vegana, japonesa e internacional","Chefs multilingües: ES/EN/FR/IT disponibles","Experiencia en villas, yates y superyates","Cobertura en Ibiza Town, Sant Antoni, Santa Gertrudis, Es Cubells, Formentera","Aprovisionamiento en el mercado de Ibiza Vila y productores locales","Chefs habituados a los estándares UHNW"],
    missionTypes: ["Villa en Ibiza","Yate y superyate","Temporada completa","Estancia semanal","Formentera","Evento privado","Residencia larga duración"],
    bookingDelay: "Reserve antes de enero para julio–agosto. Junio y septiembre: disponible hasta abril–mayo. Última hora posible pero limitada.",
    metaTitle: "Chef Privado Ibiza | +50 Chefs Seleccionados | Villas & Yates — Chefs Talents",
    metaDescription: "Contrata un chef privado en Ibiza para tu villa o yate de lujo. Más de 50 chefs seleccionados. Menús a medida, perfiles multilingües, disponibles de mayo a septiembre. Respuesta en 6h.",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?q=80&w=1200",
    longDescription: `Ibiza ya no es solo una isla de fiesta. En los últimos años se ha consolidado como uno de los destinos privados más exigentes del Mediterráneo. Las villas de lujo de Es Cubells, las fincas de Santa Gertrudis, las propiedades con vistas de Sant Josep — entornos donde la experiencia culinaria se ha vuelto tan importante como el marco en sí.

Chefs Talents cuenta con más de 50 chefs activos en su red en la isla. Perfiles que conocen Ibiza — sus mercados, sus productores, sus ritmos — y que saben adaptarse a las exigencias de una clientela internacional acostumbrada a las mejores mesas del mundo.

La temporada activa va de mayo a septiembre, con pico en julio y agosto. La demanda está extremadamente concentrada en este periodo. Los mejores perfiles están reservados desde enero por clientes habituales. Si tienes prevista una villa o un yate este verano, contáctanos ahora.`,
    zones: [{ name: "Es Cubells & Sant Josep", description: "Villas con vistas al mar, clientela ultra-discreta" },{ name: "Santa Gertrudis", description: "Fincas y residencias interiores, estancias largas" },{ name: "Ibiza Town & Talamanca", description: "Villas cerca del puerto, clientela cosmopolita" },{ name: "Sant Antoni", description: "Villas costeras, cenas al atardecer estilo Café del Mar" },{ name: "Formentera", description: "Servicio en villa y traslados entre islas desde Ibiza" },{ name: "Yates & puertos", description: "Marina Botafoch, Puerto Deportivo, fondeos privados" }],
    faqs: [{ question: "¿Cuánto cuesta un chef privado en Ibiza?", answer: "El precio de un chef privado en Ibiza oscila entre 3.500€ y 7.000€ por semana según el perfil, número de invitados, nivel de servicio y duración de la misión. Para una cena puntual, el precio comienza desde 600€ para 6 personas. Para una presencia diaria completa (desayuno, comida, cena), los perfiles sénior oscilan entre 700€ y 1.500€ al día todo incluido — compras, preparación, servicio y limpieza incluidos." },{ question: "¿Cuál es la diferencia entre Chefs Talents y Take a Chef en Ibiza?", answer: "Take a Chef es un marketplace abierto con 467 perfiles desde 60€ por persona. Chefs Talents es una selección de más de 50 chefs verificados personalmente, con coordinación humana y respuesta garantizada en menos de 6 horas. Trabajamos con clientes donde la calidad, la continuidad y la discreción son lo primero — villas de alto nivel, yates, misiones de larga duración." },{ question: "¿Puedo contratar un chef privado en un yate en Ibiza?", answer: "Sí. Varios perfiles de nuestra red ibicenca tienen experiencia náutica validada — aprovisionamiento en puerto, cocina en espacios reducidos, servicio en alta mar. Cubrimos yates en Marina Botafoch, Puerto Deportivo, y fondeos en la bahía de Ibiza o alrededor de Formentera." },{ question: "¿Con cuánta antelación debo reservar un chef privado para el verano en Ibiza?", answer: "Los mejores perfiles se reservan desde enero para la temporada alta (julio–agosto). Para junio o septiembre, la disponibilidad es accesible hasta abril–mayo. Las solicitudes de última hora son posibles pero la disponibilidad es muy limitada en pleno verano. Siempre hacemos lo posible por encontrar una solución." },{ question: "¿Los chefs de Chefs Talents en Ibiza hablan español?", answer: "Sí. La mayoría de los perfiles de nuestra red ibicenca son multilingües. Según la misión, seleccionamos chefs que se comunican en español, inglés, francés e italiano. El idioma del cliente siempre se tiene en cuenta en el proceso de selección." },{ question: "¿Chefs Talents cubre Formentera?", answer: "Sí. Varios chefs de nuestra red trabajan regularmente en Formentera. El traslado desde Ibiza está integrado en la coordinación. Contáctanos con tu solicitud específica." }],
    seoKeywords: ["chef privado Ibiza","contratar chef privado Ibiza","chef privado villa Ibiza","chef privado yate Ibiza","chef particular Ibiza","chef a domicilio Ibiza","chef privado Formentera","chef lujo Ibiza","chef villa Ibiza"],
  },

  // ════════════════════════════════════════════════════════════
  // MYKONOS
  // ════════════════════════════════════════════════════════════
  {
    slug: "chef-prive-mykonos",
    name: "Mykonos", region: "Cyclades", country: "Grèce", lang: "fr",
    heroTitle: "Chef privé Mykonos",
    heroSubtitle: "Villas de luxe dans les Cyclades & gastronomie méditerranéenne",
    description: "Mykonos est l'une des destinations les plus prisées de Méditerranée. Les villas avec vue mer accueillent une clientèle internationale en juillet–août. Les bons profils sont pris dès mars.",
    season: "Juin — Septembre (pic juillet–août)", rateRange: "3 500€ — 8 000€",
    rateDetail: "par semaine selon le nombre de convives et l'intensité du service",
    highlights: ["Fruits de mer des Cyclades & langoustes, pieuvre","Cuisine méditerranéenne contemporaine","Dîners coucher de soleil en terrasse","Producteurs locaux et marché Mykonos Town","Profils multilingues disponibles"],
    missionTypes: ["Villa Mykonos","Vue sur la mer Égée","Dîner terrasse","Séjour semaine","Mission yacht"],
    bookingDelay: "Juillet–août : réservez dès mars",
    metaTitle: "Chef Privé Mykonos | Villas Cyclades — Chefs Talents",
    metaDescription: "Chef privé à Mykonos pour votre villa dans les Cyclades. Cuisine méditerranéenne, fruits de mer locaux, dîners terrasse coucher de soleil.",
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?q=80&w=1200", featured: true,
  },
  {
    slug: "private-chef-mykonos",
    name: "Mykonos", region: "Cyclades", country: "Greece", lang: "en",
    heroTitle: "Private Chef Mykonos",
    heroSubtitle: "Luxury villas in the Cyclades & Mediterranean gastronomy",
    description: "Mykonos is one of the most sought-after destinations in the Mediterranean. Sea-view villas welcome an international clientele in July–August. The best profiles book out from March.",
    season: "June — September (peak July–August)", rateRange: "€3,500 — €8,000",
    rateDetail: "per week depending on number of guests and service level",
    highlights: ["Cyclades seafood — lobster, octopus","Contemporary Mediterranean cuisine","Sunset terrace dinners","Local producers and Mykonos Town market","Multilingual profiles available"],
    missionTypes: ["Mykonos villa","Aegean sea view","Terrace dinner","Weekly stay","Yacht mission"],
    bookingDelay: "July–August: book from March",
    metaTitle: "Private Chef Mykonos | Cyclades Villas — Chefs Talents",
    metaDescription: "Private chef in Mykonos for your villa in the Cyclades. Mediterranean cuisine, local seafood, sunset terrace dinners.",
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?q=80&w=1200",
  },
  {
    slug: "chef-privado-mykonos",
    name: "Mykonos", region: "Cícladas", country: "Grecia", lang: "es",
    heroTitle: "Chef Privado Mykonos",
    heroSubtitle: "Villas de lujo en las Cícladas & gastronomía mediterránea",
    description: "Mykonos es uno de los destinos más codiciados del Mediterráneo. Las villas con vistas al mar acogen a una clientela internacional en julio–agosto. Los mejores perfiles se reservan desde marzo.",
    season: "Junio — Septiembre (pico julio–agosto)", rateRange: "3.500€ — 8.000€",
    rateDetail: "por semana según el número de invitados e intensidad del servicio",
    highlights: ["Marisco de las Cícladas — langosta, pulpo","Cocina mediterránea contemporánea","Cenas al atardecer en terraza","Productores locales y mercado de Mykonos Town","Perfiles multilingües disponibles"],
    missionTypes: ["Villa Mykonos","Vista al mar Egeo","Cena en terraza","Estancia semanal","Misión yate"],
    bookingDelay: "Julio–agosto: reserve desde marzo",
    metaTitle: "Chef Privado Mykonos | Villas Cícladas — Chefs Talents",
    metaDescription: "Chef privado en Mykonos para su villa en las Cícladas. Cocina mediterránea, marisco local, cenas al atardecer en terraza.",
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?q=80&w=1200",
  },

  // ════════════════════════════════════════════════════════════
  // SARDAIGNE
  // ════════════════════════════════════════════════════════════
  {
    slug: "chef-prive-sardaigne",
    name: "Sardaigne", region: "Costa Smeralda", country: "Italie", lang: "fr",
    heroTitle: "Chef privé Sardaigne",
    heroSubtitle: "Costa Smeralda et Porto Cervo — l'excellence culinaire privée",
    description: "La Costa Smeralda est l'une des destinations les plus exclusives de Méditerranée. Porto Cervo, Portisco, Baia Sardinia concentrent des villas et superyachts dont les propriétaires attendent une cuisine d'exception.",
    season: "Juin — Septembre", rateRange: "3 500€ — 8 000€",
    rateDetail: "par semaine selon le nombre de convives et le profil",
    highlights: ["Bottarga de Cabras, pecorino sardo, langoustes","Cuisine sarde contemporaine maîtrisée","Producteurs locaux d'Olbia et de l'île","Expérience villa et superyacht","Profils multilingues IT/EN/FR"],
    missionTypes: ["Porto Cervo","Portisco","Baia Sardinia","Villa Costa Smeralda","Superyacht"],
    bookingDelay: "Juillet : réservez dès avril",
    metaTitle: "Chef Privé Sardaigne | Costa Smeralda & Porto Cervo — Chefs Talents",
    metaDescription: "Chef privé en Sardaigne pour votre villa ou yacht sur la Costa Smeralda. Porto Cervo, Portisco. Cuisine sarde et gastronomique, discrétion totale.",
    image: "https://images.unsplash.com/photo-1499678329028-101435549a4e?q=80&w=1200",
  },
  {
    slug: "private-chef-sardinia",
    name: "Sardinia", region: "Costa Smeralda", country: "Italy", lang: "en",
    heroTitle: "Private Chef Sardinia",
    heroSubtitle: "Costa Smeralda and Porto Cervo — private culinary excellence",
    description: "The Costa Smeralda is one of the most exclusive destinations in the Mediterranean. Porto Cervo, Portisco and Baia Sardinia concentrate villas and superyachts whose owners expect exceptional cuisine.",
    season: "June — September", rateRange: "€3,500 — €8,000",
    rateDetail: "per week depending on number of guests and profile",
    highlights: ["Bottarga di Cabras, pecorino sardo, Sardinian lobster","Contemporary Sardinian cuisine mastered","Local producers from Olbia and the island","Villa and superyacht experience","Multilingual profiles IT/EN/FR"],
    missionTypes: ["Porto Cervo","Portisco","Baia Sardinia","Costa Smeralda villa","Superyacht"],
    bookingDelay: "July: book from April",
    metaTitle: "Private Chef Sardinia | Costa Smeralda & Porto Cervo — Chefs Talents",
    metaDescription: "Private chef in Sardinia for your villa or yacht on the Costa Smeralda. Porto Cervo, Portisco. Sardinian and gastronomic cuisine, total discretion.",
    image: "https://images.unsplash.com/photo-1499678329028-101435549a4e?q=80&w=1200",
  },
  {
    slug: "chef-privado-cerdena",
    name: "Cerdeña", region: "Costa Esmeralda", country: "Italia", lang: "es",
    heroTitle: "Chef Privado Cerdeña",
    heroSubtitle: "Costa Esmeralda y Porto Cervo — excelencia culinaria privada",
    description: "La Costa Esmeralda es uno de los destinos más exclusivos del Mediterráneo. Porto Cervo, Portisco y Baia Sardinia concentran villas y superyates cuyos propietarios esperan una cocina excepcional.",
    season: "Junio — Septiembre", rateRange: "3.500€ — 8.000€",
    rateDetail: "por semana según el número de invitados y el perfil",
    highlights: ["Bottarga de Cabras, pecorino sardo, langosta sarda","Cocina sarda contemporánea dominada","Productores locales de Olbia y la isla","Experiencia en villa y superyate","Perfiles multilingües IT/EN/FR"],
    missionTypes: ["Porto Cervo","Portisco","Baia Sardinia","Villa Costa Esmeralda","Superyate"],
    bookingDelay: "Julio: reserve desde abril",
    metaTitle: "Chef Privado Cerdeña | Costa Esmeralda & Porto Cervo — Chefs Talents",
    metaDescription: "Chef privado en Cerdeña para su villa o yate en la Costa Esmeralda. Porto Cervo, Portisco. Cocina sarda y gastronómica, discreción total.",
    image: "https://images.unsplash.com/photo-1499678329028-101435549a4e?q=80&w=1200",
  },

  // ════════════════════════════════════════════════════════════
  // PORTUGAL
  // ════════════════════════════════════════════════════════════
  {
    slug: "chef-prive-portugal",
    name: "Portugal", region: "Algarve & Lisbonne", country: "Portugal", lang: "fr",
    heroTitle: "Chef privé Portugal",
    heroSubtitle: "Algarve, Lisbonne et villas de luxe — la nouvelle destination premium",
    description: "Le Portugal s'est imposé comme l'une des destinations premium les plus demandées d'Europe. L'Algarve et ses villas, Lisbonne et ses quintas — un marché en forte croissance avec encore de bonnes disponibilités.",
    season: "Avril — Octobre", rateRange: "2 500€ — 5 000€",
    rateDetail: "par semaine, meilleur rapport qualité-prix d'Europe",
    highlights: ["Fruits de mer exceptionnels — percebes, langoustes","Huile d'olive et vins du Douro premium","Cuisine contemporaine portugaise","Quinta do Lago, Vale do Lobo, Vilamoura","Disponibilités plus flexibles qu'en France"],
    missionTypes: ["Villa Algarve","Quinta Lisbonne","Vilamoura","Vale do Lobo","Quinta do Lago"],
    bookingDelay: "Disponibilités plus accessibles qu'en haute saison méditerranéenne",
    metaTitle: "Chef Privé Portugal | Algarve & Lisbonne — Chefs Talents",
    metaDescription: "Chef privé au Portugal pour votre villa en Algarve ou quinta à Lisbonne. Fruits de mer, cuisine portugaise contemporaine. Meilleur rapport qualité-prix d'Europe.",
    image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?q=80&w=1200",
  },
  {
    slug: "private-chef-portugal",
    name: "Portugal", region: "Algarve & Lisbon", country: "Portugal", lang: "en",
    heroTitle: "Private Chef Portugal",
    heroSubtitle: "Algarve, Lisbon and luxury villas — Europe's new premium destination",
    description: "Portugal has established itself as one of Europe's most in-demand premium destinations. The Algarve and its villas, Lisbon and its quintas — a fast-growing market with still-accessible availability.",
    season: "April — October", rateRange: "€2,500 — €5,000",
    rateDetail: "per week, best value for money in Europe",
    highlights: ["Exceptional seafood — percebes, lobster","Premium olive oil and Douro wines","Contemporary Portuguese cuisine","Quinta do Lago, Vale do Lobo, Vilamoura","More flexible availability than France"],
    missionTypes: ["Algarve villa","Lisbon quinta","Vilamoura","Vale do Lobo","Quinta do Lago"],
    bookingDelay: "More accessible availability than peak Mediterranean season",
    metaTitle: "Private Chef Portugal | Algarve & Lisbon — Chefs Talents",
    metaDescription: "Private chef in Portugal for your Algarve villa or Lisbon quinta. Seafood, contemporary Portuguese cuisine. Best value for money in Europe.",
    image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?q=80&w=1200",
  },
  {
    slug: "chef-privado-portugal",
    name: "Portugal", region: "Algarve & Lisboa", country: "Portugal", lang: "es",
    heroTitle: "Chef Privado Portugal",
    heroSubtitle: "Algarve, Lisboa y villas de lujo — el nuevo destino premium de Europa",
    description: "Portugal se ha consolidado como uno de los destinos premium más solicitados de Europa. El Algarve y sus villas, Lisboa y sus quintas — un mercado en fuerte crecimiento con buena disponibilidad todavía.",
    season: "Abril — Octubre", rateRange: "2.500€ — 5.000€",
    rateDetail: "por semana, mejor relación calidad-precio de Europa",
    highlights: ["Marisco excepcional — percebes, langosta","Aceite de oliva y vinos del Duero premium","Cocina portuguesa contemporánea","Quinta do Lago, Vale do Lobo, Vilamoura","Disponibilidad más flexible que en Francia"],
    missionTypes: ["Villa Algarve","Quinta Lisboa","Vilamoura","Vale do Lobo","Quinta do Lago"],
    bookingDelay: "Disponibilidad más accesible que en temporada alta mediterránea",
    metaTitle: "Chef Privado Portugal | Algarve & Lisboa — Chefs Talents",
    metaDescription: "Chef privado en Portugal para su villa en el Algarve o quinta en Lisboa. Marisco, cocina portuguesa contemporánea. Mejor relación calidad-precio de Europa.",
    image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?q=80&w=1200",
  },
];

// ─────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────
export const getDestinationBySlug = (slug: string) =>
  destinations.find((d) => d.slug === slug);

export const getAllDestinationSlugs = () =>
  destinations.map((d) => d.slug);

export const getFeaturedDestinations = () =>
  destinations.filter((d) => d.featured);
