export interface Destination {
  slug: string;
  name: string;
  region: string;
  country: string;
  lang: "fr" | "en";
  heroTitle: string;
  heroSubtitle: string;
  description: string;
  season: string;
  rateRange: string;
  rateDetail: string;
  highlights: string[];
  missionTypes: string[];
  bookingDelay: string;
  metaTitle: string;
  metaDescription: string;
  image: string;
  featured?: boolean;
  // ── Champs enrichis (optionnels) ──────────────────────────
  longDescription?: string;
  zones?: Array<{ name: string; description: string }>;
  faqs?: Array<{ question: string; answer: string }>;
  seoKeywords?: string[];
}

export const destinations: Destination[] = [
  // ── FRANCE ────────────────────────────────────────────────
  {
    slug: "chef-prive-cote-azur",
    name: "Côte d'Azur",
    region: "Provence-Alpes-Côte d'Azur",
    country: "France",
    lang: "fr",
    heroTitle: "Chef privé Côte d'Azur",
    heroSubtitle: "Villas, yachts et résidences privées de Saint-Tropez à Monaco",
    description: "La Côte d'Azur concentre la plus forte densité de résidences privées haut de gamme d'Europe. De juin à septembre, la demande en chefs privés explose. Les meilleurs profils se réservent dès février pour la saison estivale.",
    season: "Avril — Octobre (pic juin–août)",
    rateRange: "3 500€ — 10 000€",
    rateDetail: "par semaine selon le profil et l'intensité du service",
    highlights: [
      "Chefs mobiles couvrant toute la Riviera",
      "Profils multilingues disponibles",
      "Expérience villas, yachts et résidences UHNW",
      "Approvisionnement marchés locaux provençaux",
      "Discrétion et confidentialité garanties",
    ],
    missionTypes: ["Villa privée", "Yacht", "Résidence longue durée", "Événement privé", "Famille UHNW"],
    bookingDelay: "Réservez à l'avance pour avoir les meilleurs profils durant la haute saison",
    metaTitle: "Chef Privé Côte d'Azur | Villas & Yachts — Chefs Talents",
    metaDescription: "Trouvez un chef privé sur la Côte d'Azur pour votre villa ou yacht. Saint-Tropez, Cannes, Antibes, Monaco, Cap Ferrat. Sélection rigoureuse, discrétion totale.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=1200",
    featured: true,
  },
  {
    slug: "chef-prive-saint-tropez",
    name: "Saint-Tropez",
    region: "Var",
    country: "France",
    lang: "fr",
    heroTitle: "Chef privé Saint-Tropez",
    heroSubtitle: "Le marché le plus exigeant de Méditerranée",
    description: "Saint-Tropez impose des standards culinaires particuliers. Les villas du golfe accueillent une clientèle habituée aux meilleures tables du monde. Le chef privé doit délivrer un niveau gastronomique constant avec une maîtrise parfaite des produits méditerranéens locaux.",
    season: "Juin — Septembre (pics juillet–août)",
    rateRange: "3 500€ — 10 000€",
    rateDetail: "par semaine selon le profil et l'intensité du service",
    highlights: [
      "Chefs formés en restaurant étoilé disponibles",
      "Connaissance du marché de Saint-Tropez",
      "Réseau de producteurs locaux du Var",
      "Profils yacht pour missions mer + villa",
      "Réservation recommandée dès mars",
    ],
    missionTypes: ["Villa golfe de Saint-Tropez", "Yacht en mouillage", "Ramatuelle", "Gassin", "Port Grimaud"],
    bookingDelay: "Juillet–août complets dès le mois de mars pour les meilleurs profils",
    metaTitle: "Chef Privé Saint-Tropez | Villas & Yachts — Chefs Talents",
    metaDescription: "Chef privé à Saint-Tropez pour votre villa ou yacht dans le golfe. Profils gastronomiques sélectionnés, discrétion totale, coordination complète.",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=1200",
    featured: true,
  },
  {
    slug: "chef-prive-cannes",
    name: "Cannes",
    region: "Alpes-Maritimes",
    country: "France",
    lang: "fr",
    heroTitle: "Chef privé Cannes",
    heroSubtitle: "Villas, événements et Festival — excellence culinaire privée",
    description: "Cannes concentre une demande exceptionnelle en chefs privés, amplifiée par le Festival et les événements internationaux. Les villas des hauteurs, les yachts du Vieux-Port et les résidences du Cap d'Antibes créent un marché dense et exigeant toute l'année.",
    season: "Toute l'année (pic mai Festival + juin–août)",
    rateRange: "3 500€ — 10 000€",
    rateDetail: "par semaine selon le profil et l'intensité du service",
    highlights: [
      "Chefs privé expérimentés",
      "Couverture Festival de Cannes en mai",
      "Profils multilingues",
      "Villas des hauteurs et yachts du port",
      "Disponibilités limitées en période Festival",
    ],
    missionTypes: ["Villa Cannes", "Yacht Vieux-Port", "Événement Festival", "Résidence Croisette", "Cap d'Antibes"],
    bookingDelay: "Festival de Cannes (mai) : réservez à l'avance",
    metaTitle: "Chef Privé Cannes | Festival & Villas — Chefs Talents",
    metaDescription: "Chef privé à Cannes pour votre villa, yacht ou événement pendant le Festival. Profils sélectionnés, disponibles toute l'année sur la Côte d'Azur.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=1200",
  },
  {
    slug: "chef-prive-antibes",
    name: "Antibes",
    region: "Alpes-Maritimes",
    country: "France",
    lang: "fr",
    heroTitle: "Chef privé Antibes & Cap d'Antibes",
    heroSubtitle: "Entre pinèdes et mer — résidences discrètes et séjours longue durée",
    description: "Antibes et le Cap d'Antibes offrent un cadre plus résidentiel que Saint-Tropez. Les villas nichées dans les pinèdes accueillent des séjours souvent longs, avec une clientèle attachée à la discrétion et à la qualité du quotidien.",
    season: "Mai — Octobre",
    rateRange: "2 500€ — 10 000€",
    rateDetail: "par semaine selon la durée et le niveau de service",
    highlights: [
      "Marché provençal d'Antibes parmi les meilleurs",
      "Profils longue durée disponibles",
      "Accès facile depuis Nice et Cannes",
      "Cuisine de résidence quotidienne maîtrisée",
      "Clientèle fidèle chefs intégrés dans le rythme de la maison",
    ],
    missionTypes: ["Cap d'Antibes", "Juan-les-Pins", "Résidence longue durée", "Villa familiale", "Yacht port Vauban"],
    bookingDelay: "Disponibilités plus flexibles qu'à Saint-Tropez",
    metaTitle: "Chef Privé Antibes & Cap d'Antibes — Chefs Talents",
    metaDescription: "Chef privé à Antibes et Cap d'Antibes pour villas et résidences privées. Séjours longue durée, familles UHNW, discrétion totale.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=1200",
  },
  {
    slug: "chef-prive-monaco",
    name: "Monaco",
    region: "Principauté de Monaco",
    country: "Monaco",
    lang: "fr",
    heroTitle: "Chef privé Monaco",
    heroSubtitle: "La Principauté la plus exigeante d'Europe",
    description: "Monaco est la destination la plus exigeante d'Europe pour les chefs privés. NDA systématiques, expérience UHNW validée, présentation irréprochable. Les profils qui y opèrent ont une catégorie à part.",
    season: "Toute l'année (pic Grand Prix mai + été)",
    rateRange: "5 000€ — 12 000€",
    rateDetail: "par semaine, profils senior uniquement",
    highlights: [
      "NDA et confidentialité absolue",
      "Références UHNW vérifiées",
      "Expérience résidences et superyachts",
      "Langues : FR/EN/RU selon les clients",
      "Accès réseau Principauté maîtrisé",
    ],
    missionTypes: ["Résidence privée", "Superyacht port Hercule", "Grand Prix Monaco", "Penthouse", "Family Office"],
    bookingDelay: "Grand Prix (mai) : réservez 6 mois à l'avance",
    metaTitle: "Chef Privé Monaco | UHNW & Superyachts — Chefs Talents",
    metaDescription: "Chef privé à Monaco pour résidences et yachts. Profils d'exception, NDA systématique, discrétion absolue. Chefs Talents — référence pour l'hospitalité privée.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1200",
    featured: true,
  },
  {
    slug: "chef-prive-nice",
    name: "Nice",
    region: "Alpes-Maritimes",
    country: "France",
    lang: "fr",
    heroTitle: "Chef privé Nice",
    heroSubtitle: "Entre mer et collines résidences et villas niçoises",
    description: "Nice est la capitale de la Côte d'Azur et un hub logistique pour les missions de toute la Riviera. Les chefs basés à Nice interviennent sur l'ensemble du territoire — Antibes, Cannes, Monaco, Cap Ferrat.",
    season: "Toute l'année",
    rateRange: "3 000€ — 10 000€",
    rateDetail: "par semaine selon le profil et l'intensité du service",
    highlights: [
      "Hub logistique pour toute la Côte d'Azur",
      "Marché du Cours Saleya produits exceptionnels",
      "Profils disponibles toute l'année",
      "Mont Boron, Cimiez, arrière-pays niçois",
    ],
    missionTypes: ["Villa Nice", "Résidence Cimiez", "Mont Boron", "Arrière-pays niçois", "Mission courte"],
    bookingDelay: "Disponibilités flexibles hors saison",
    metaTitle: "Chef Privé Nice | Villas & Résidences | Chefs Talents",
    metaDescription: "Chef privé à Nice pour villas et résidences privées. Cuisine niçoise et gastronomique.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=1200",
  },
  {
    slug: "chef-prive-cap-ferrat",
    name: "Cap Ferrat",
    region: "Alpes-Maritimes",
    country: "France",
    lang: "fr",
    heroTitle: "Chef privé Cap Ferrat",
    heroSubtitle: "La presqu'île la plus exclusive de France",
    description: "Le Cap Ferrat est la presqu'île la plus exclusive de France. Entre Nice et Monaco, ses villas centenaires accueillent une clientèle parmi les plus discrètes et les plus exigeantes de la Côte d'Azur.",
    season: "Mai — Octobre (résidences toute l'année)",
    rateRange: "5 000€ — 15 000€",
    rateDetail: "par semaine, missions souvent longue durée",
    highlights: [
      "Résidences longue durée fréquentes",
      "Clientèle ultra-discrète et fidèle",
      "Intégration dans le rythme de la maison",
      "Profils habitués aux environnements UHNW",
    ],
    missionTypes: ["Villa Cap Ferrat", "Résidence longue durée", "Famille UHNW", "Mission saisonnière", "Villefranche-sur-Mer"],
    bookingDelay: "Missions souvent réservées plusieurs mois à l'avance",
    metaTitle: "Chef Privé Cap Ferrat | Villas d'Exception — Chefs Talents",
    metaDescription: "Chef privé au Cap Ferrat pour villas et résidences privées. La presqu'île la plus exclusive de France. Discrétion absolue, intégration longue durée.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=1200",
  },
  {
    slug: "chef-prive-courchevel",
    name: "Courchevel",
    region: "Savoie",
    country: "France",
    lang: "fr",
    heroTitle: "Chef privé Courchevel",
    heroSubtitle: "Chalets de luxe et gastronomie alpine — saison ski",
    description: "Courchevel 1850 est la station la plus prestigieuse des Alpes françaises. Les chalets du Jardin Alpin accueillent une clientèle internationale dont les attentes culinaires rivalisent avec les meilleures tables parisiennes. Les meilleurs chefs sont réservés 6 à 12 mois à l'avance.",
    season: "Décembre — Avril (Noël/Nouvel An + février)",
    rateRange: "3 500€ — 25 000€",
    rateDetail: "par semaine, tarif maximum période Noël",
    highlights: [
      "Chefs formés haute cuisine disponibles",
      "Maîtrise pâtisserie fine pour tea-times",
      "Expérience cuisine d'altitude validée",
      "Langues : FR/EN/RU selon les chalets",
    ],
    missionTypes: ["Chalet Courchevel 1850", "Jardin Alpin", "Bellecôte", "Famille ski", "Nouvel An"],
    bookingDelay: "Noël/Nouvel An : réservez à l'avance",
    metaTitle: "Chef Privé Courchevel | Chalets de Luxe | Chefs Talents",
    metaDescription: "Chef privé à Courchevel 1850 pour votre chalet de luxe. Gastronomie alpine, tea-times, dîners d'exception après le ski. Sélection rigoureuse.",
    image: "https://images.unsplash.com/photo-1516571589254-46487e38c92a?q=80&w=1200",
    featured: true,
  },
  {
    slug: "chef-prive-megeve",
    name: "Megève",
    region: "Haute-Savoie",
    country: "France",
    lang: "fr",
    heroTitle: "Chef privé Megève",
    heroSubtitle: "La station la plus élégante des Alpes françaises",
    description: "Megève cultive un art de vivre discret et raffiné où la gastronomie occupe une place centrale. Entourée de producteurs d'exception — fromagers de Haute-Savoie, charcutiers savoyards — la destination impose un chef qui sait travailler le terroir.",
    season: "Décembre — Mars + Juillet — Août",
    rateRange: "3 000€ — 13 000€",
    rateDetail: "par semaine selon la saison",
    highlights: [
      "Cuisine terroir savoyard et gastronomique",
      "Profils avec sensibilité cuisine de saison",
      "Ambiance chalet intime et raffinée",
      "Double saison ski + été disponible",
    ],
    missionTypes: ["Chalet Megève", "Résidence ski", "Mission été", "Famille longue durée", "Événement privé"],
    bookingDelay: "Saison ski : réservez plusieurs mois à l'avance pour avoir accès aux meilleurs profils",
    metaTitle: "Chef Privé Megève | Chalets & Art de Vivre Alpin | Chefs Talents",
    metaDescription: "Chef privé à Megève pour votre chalet. Cuisine savoyarde et gastronomique, tea-times, dîners après le ski. La station la plus élégante des Alpes.",
    image: "https://images.unsplash.com/photo-1516571589254-46487e38c92a?q=80&w=1200",
  },
  {
    slug: "chef-prive-val-disere",
    name: "Val d'Isère",
    region: "Savoie",
    country: "France",
    lang: "fr",
    heroTitle: "Chef privé Val d'Isère",
    heroSubtitle: "Chalets d'exception en Tarentaise — saison ski",
    description: "Val d'Isère attire une clientèle sportive et internationale dans des chalets parmi les plus luxueux des Alpes. L'altitude (1 850m) et l'enclavement imposent une logistique rigoureuse que seuls les chefs expérimentés maîtrisent.",
    season: "Décembre — Avril",
    rateRange: "3 000€ — 12 000€",
    rateDetail: "par semaine selon la période",
    highlights: [
      "Logistique altitude maîtrisée",
      "Petits-déjeuners denses avant les pistes",
      "Tea-times et dîners gastronomiques",
    ],
    missionTypes: ["Chalet Val d'Isère", "Famille ski", "Nouvel An", "Séjour sportif", "Mission semaine"],
    bookingDelay: "Noël/Nouvel An : réservez 6 mois à l'avance",
    metaTitle: "Chef Privé Val d'Isère | Chalets de Luxe | Chefs Talents",
    metaDescription: "Chef privé à Val d'Isère pour votre chalet de luxe. Logistique altitude maîtrisée, gastronomie alpine, disponible toute la saison ski.",
    image: "https://images.unsplash.com/photo-1516571589254-46487e38c92a?q=80&w=1200",
  },
  {
    slug: "chef-prive-biarritz",
    name: "Biarritz",
    region: "Pays Basque",
    country: "France",
    lang: "fr",
    heroTitle: "Chef privé Biarritz",
    heroSubtitle: "Villas basques et Côte d'Argent — gastronomie du Pays Basque",
    description: "Biarritz et la Côte basque constituent un marché en forte croissance. Les villas des hauteurs accueillent une clientèle parisienne et internationale attirée par le terroir gastronomique exceptionnel du Pays Basque.",
    season: "Juin — Septembre + week-ends toute l'année",
    rateRange: "3 200€ — 11 000€",
    rateDetail: "par semaine selon le profil",
    highlights: [
      "Thon rouge de Saint-Jean-de-Luz en saison",
      "Cuisine basque contemporaine maîtrisée",
      "Palombe et produits de saison",
      "Marché des Halles de Biarritz",
    ],
    missionTypes: ["Villa Biarritz", "Saint-Jean-de-Luz", "Anglet", "Résidence côtière", "Événement basque"],
    bookingDelay: "Juillet–août : réservez 2 mois à l'avance",
    metaTitle: "Chef Privé Biarritz & Pays Basque — Chefs Talents",
    metaDescription: "Chef privé à Biarritz pour votre villa sur la Côte basque. Gastronomie basque, produits locaux d'exception, discrétion totale.",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=1200",
  },

  // ── EUROPE ─────────────────────────────────────────────────
  {
    slug: "chef-prive-ibiza",
    name: "Ibiza",
    region: "Îles Baléares",
    country: "Espagne",
    lang: "fr",
    heroTitle: "Chef privé Ibiza",
    heroSubtitle: "Plus de 50 chefs sélectionnés pour villas, yachts et résidences aux Baléares",
    description: "Ibiza s'est imposée comme l'une des destinations les plus demandées de Méditerranée pour les chefs privés. Avec plus de 50 chefs actifs dans notre réseau sur l'île, Chefs Talents est la référence française pour les villas de luxe, yachts et résidences privées à Ibiza. Saison concentrée de mai à septembre : les meilleurs profils se réservent dès janvier.",
    season: "Mai — Septembre (pic juin–août)",
    rateRange: "3 500€ — 7 000€",
    rateDetail: "par semaine selon le profil, le nombre de personne, la durée et l'intensité du service",
    highlights: [
      "50+ chefs actifs dans notre réseau sur l'île",
      "Cuisine méditerranéenne, végane, internationale, japonaise",
      "Profils multilingues ES/EN/FR/IT disponibles",
      "Expérience villas, yachts et superyachts",
      "Couverture Ibiza Town, Sant Antoni, Santa Gertrudis, Es Cubells, Formentera",
      "Approvisionnement marché d'Ibiza Vila et producteurs locaux",
      "Chefs habitués aux standards UHNW",
    ],
    missionTypes: [
      "Villa Ibiza",
      "Yacht et superyacht",
      "Saison complète",
      "Séjour semaine",
      "Formentera",
      "Événement privé",
      "Résidence longue durée",
    ],
    bookingDelay: "Saison complète : réservez dès janvier : profils limités en juillet–août",
    metaTitle: "Chef Privé Ibiza | 50+ Chefs Sélectionnés | Villas & Yachts — Chefs Talents",
    metaDescription: "Chef privé à Ibiza pour votre villa ou yacht de luxe. Plus de 50 chefs sélectionnés dans notre réseau. Cuisine sur-mesure, profils multilingues, disponibles de mai à septembre. Réponse en 6h.",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?q=80&w=1200",
    featured: true,
    longDescription: `Ibiza n'est plus seulement une île de fête. Depuis plusieurs années, elle s'est imposée comme l'une des destinations privées les plus exigeantes de Méditerranée. Les villas de luxe d'Es Cubells, les fincas de Santa Gertrudis, les propriétés avec vue de Sant Josep  autant d'environnements où l'expérience culinaire est devenue aussi importante que le cadre.

Chefs Talents dispose de plus de 50 chefs actifs dans son réseau sur l'île. Des profils qui connaissent Ibiza : ses marchés, ses producteurs, ses rythmes  et qui savent s'adapter aux exigences d'une clientèle internationale habituée aux meilleures tables du monde.

La saison active dure de mai à septembre, avec un pic en juillet et août. La demande est extrêmement concentrée sur cette période. Les meilleurs profils sont réservés dès janvier par des clients réguliers. Si vous prévoyez une villa ou un yacht cet été, contactez-nous maintenant.`,
    zones: [
      { name: "Es Cubells & Sant Josep", description: "Villas avec vue mer, clientèle ultra-discrète" },
      { name: "Santa Gertrudis", description: "Fincas et résidences intérieures, séjours longue durée" },
      { name: "Ibiza Town & Talamanca", description: "Villas proches du port, clientèle cosmopolite" },
      { name: "Sant Antoni", description: "Villas côtières, couchers de soleil Café del Mar" },
      { name: "Formentera", description: "Villas et transferts inter-îles, accessible depuis Ibiza" },
      { name: "Yachts & ports", description: "Marina Botafoch, Puerto Deportivo, mouillages privés" },
    ],
    faqs: [
      {
        question: "Combien coûte un chef privé à Ibiza ?",
        answer: "Le tarif d'un chef privé à Ibiza varie entre 3 500€ et 7 000€ par semaine selon le profil, le nombre de convives, le niveau de service et la durée de la mission. Pour un dîner ponctuel, comptez à partir de 600€ pour 6 personnes. Pour une présence quotidienne (petit-déjeuner, déjeuner, dîner), les profils seniors se situent entre 700€ et 1 500€ par jour tout compris. Ces tarifs incluent les courses, la préparation, le service et le nettoyage.",
      },
      {
        question: "Quelle est la différence entre Chefs Talents et Take a Chef à Ibiza ?",
        answer: "Take a Chef est une marketplace ouverte à tous les profils à partir de 60€ par personne. Chefs Talents est une sélection de 50+ chefs vérifiés, avec une coordination humaine et une réponse garantie en moins de 6 heures. Nous intervenons pour des missions où la qualité, la continuité et la discrétion priment  villas haut de gamme, yachts, missions longue durée.",
      },
      {
        question: "Peut-on avoir un chef privé sur un yacht à Ibiza ?",
        answer: "Oui. Plusieurs profils de notre réseau ibicenco ont une expérience yachting validée approvisionnement en port, cuisine en espace contraint, service à la mer. Nous couvrons les yachts à quai à Marina Botafoch, Puerto Deportivo, et les mouillages dans la baie d'Ibiza ou autour de Formentera.",
      },
      {
        question: "Jusqu'à quand peut-on réserver un chef privé pour l'été à Ibiza ?",
        answer: "Les meilleurs profils sont réservés dès janvier pour la haute saison (juillet–août). Si vous cherchez pour juin ou septembre, des disponibilités restent accessibles jusqu'en avril–mai. En cas de besoin de dernière minute, nous faisons notre possible pour trouver une solution, mais les disponibilités sont fortement réduites en plein été.",
      },
      {
        question: "Les chefs de Chefs Talents à Ibiza parlent-ils anglais ?",
        answer: "La majorité des profils de notre réseau ibicenco sont multilingues. Selon les missions, nous sélectionnons des chefs capables de communiquer en espagnol, anglais, français et parfois italien. La langue du client est toujours prise en compte lors du matching.",
      },
      {
        question: "Est-ce que Chefs Talents couvre Formentera ?",
        answer: "Oui. Plusieurs chefs de notre réseau interviennent régulièrement à Formentera. Le déplacement depuis Ibiza est intégré dans la coordination. Contactez-nous pour votre demande spécifique.",
      },
    ],
    seoKeywords: [
      "chef privé Ibiza",
      "private chef Ibiza",
      "chef cuisiner villa Ibiza",
      "chef yacht Ibiza",
      "cuisinier privé Ibiza",
      "chef à domicile Ibiza",
      "hire private chef Ibiza",
      "chef Formentera",
      "chef privé Baléares",
    ],
  },
  {
    slug: "chef-prive-mykonos",
    name: "Mykonos",
    region: "Cyclades",
    country: "Grèce",
    lang: "fr",
    heroTitle: "Chef privé Mykonos",
    heroSubtitle: "Villas de luxe dans les Cyclades & gastronomie méditerranéenne",
    description: "Mykonos est l'une des destinations les plus prisées de Méditerranée. Les villas avec vue mer accueillent une clientèle internationale en juillet–août. Les bons profils sont pris dès mars.",
    season: "Juin — Septembre (pic juillet–août)",
    rateRange: "3 000€ — 11 000€",
    rateDetail: "par semaine selon le profil",
    highlights: [
      "Fruits de mer des Cyclades & langoustes, pieuvre",
      "Cuisine méditerranéenne contemporaine",
      "Dîners coucher de soleil en terrasse",
      "Producteurs locaux et marché Mykonos Town",
      "Profils multilingues disponibles",
    ],
    missionTypes: ["Villa Mykonos", "Vue sur la mer Égée", "Dîner terrasse", "Séjour semaine", "Mission yacht"],
    bookingDelay: "Juillet–août : réservez dès mars",
    metaTitle: "Chef Privé Mykonos | Villas Cyclades — Chefs Talents",
    metaDescription: "Chef privé à Mykonos pour votre villa dans les Cyclades. Cuisine méditerranéenne, fruits de mer locaux, dîners terrasse coucher de soleil.",
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?q=80&w=1200",
    featured: true,
  },
  {
    slug: "chef-prive-sardaigne",
    name: "Sardaigne",
    region: "Costa Smeralda",
    country: "Italie",
    lang: "fr",
    heroTitle: "Chef privé Sardaigne",
    heroSubtitle: "Costa Smeralda et Porto Cervo — l'excellence culinaire privée",
    description: "La Costa Smeralda est l'une des destinations les plus exclusives de Méditerranée. Porto Cervo, Portisco, Baia Sardinia concentrent des villas et superyachts dont les propriétaires attendent une cuisine d'exception.",
    season: "Juin — Septembre",
    rateRange: "3 200€ — 12 000€",
    rateDetail: "par semaine selon le profil",
    highlights: [
      "Bottarga de Cabras, pecorino sardo, langoustes",
      "Cuisine sarde contemporaine maîtrisée",
      "Producteurs locaux d'Olbia et de l'île",
      "Expérience villa et superyacht",
      "Profils multilingues IT/EN/FR",
    ],
    missionTypes: ["Porto Cervo", "Portisco", "Baia Sardinia", "Villa Costa Smeralda", "Superyacht"],
    bookingDelay: "Juillet : réservez dès avril",
    metaTitle: "Chef Privé Sardaigne | Costa Smeralda & Porto Cervo — Chefs Talents",
    metaDescription: "Chef privé en Sardaigne pour votre villa ou yacht sur la Costa Smeralda. Porto Cervo, Portisco. Cuisine sarde et gastronomique, discrétion totale.",
    image: "https://images.unsplash.com/photo-1499678329028-101435549a4e?q=80&w=1200",
  },
  {
    slug: "chef-prive-portugal",
    name: "Portugal",
    region: "Algarve & Lisbonne",
    country: "Portugal",
    lang: "fr",
    heroTitle: "Chef privé Portugal",
    heroSubtitle: "Algarve, Lisbonne et villas de luxe — la nouvelle destination premium",
    description: "Le Portugal s'est imposé comme l'une des destinations premium les plus demandées d'Europe. L'Algarve et ses villas, Lisbonne et ses quintas — un marché en forte croissance avec encore de bonnes disponibilités.",
    season: "Avril — Octobre",
    rateRange: "2 500€ — 8 000€",
    rateDetail: "par semaine, meilleur rapport qualité-prix d'Europe",
    highlights: [
      "Fruits de mer exceptionnels — percebes, langoustes",
      "Huile d'olive et vins du Douro premium",
      "Cuisine contemporaine portugaise",
      "Quinta do Lago, Vale do Lobo, Vilamoura",
      "Disponibilités plus flexibles qu'en France",
    ],
    missionTypes: ["Villa Algarve", "Quinta Lisbonne", "Vilamoura", "Vale do Lobo", "Quinta do Lago"],
    bookingDelay: "Disponibilités plus accessibles qu'en haute saison méditerranéenne",
    metaTitle: "Chef Privé Portugal | Algarve & Lisbonne — Chefs Talents",
    metaDescription: "Chef privé au Portugal pour votre villa en Algarve ou quinta à Lisbonne. Fruits de mer, cuisine portugaise contemporaine. Meilleur rapport qualité-prix d'Europe.",
    image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?q=80&w=1200",
  },
];

export const getDestinationBySlug = (slug: string) =>
  destinations.find((d) => d.slug === slug);

export const getAllDestinationSlugs = () =>
  destinations.map((d) => d.slug);

export const getFeaturedDestinations = () =>
  destinations.filter((d) => d.featured);
